---
title: "EastRiver_rhizon-icp"
author: "CGA"
date: "April 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary packages
library(tidyverse)
library(readxl)
library(lubridate)
# Set working directory
setwd("~/east-river/")
```

## Load and tidy rhizon ICP-MS data
```{r}
rhiz_icp <- read_excel("Data/MC_rhizon_Summer2018_EastRiver_datasum_LBL.xlsx", skip=1)[-c(320:322),]

rhiz_icp$id_r <- as.numeric(rhiz_icp$id_r)
rhiz_icp$position_mct2 <- as.numeric(rhiz_icp$position_mct2)

# make "BDL" = 0
rhiz_icp$NO3[rhiz_icp$NO3 == "BDL"] <- 0
rhiz_icp$SO4[rhiz_icp$SO4 == "BDL"] <- 0
rhiz_icp$Fe[rhiz_icp$Fe == "BDL"] <- 0

# make values numeric
rhiz_icp$Fe <- as.numeric(rhiz_icp$Fe)
rhiz_icp$NO3 <- as.numeric(rhiz_icp$NO3)
rhiz_icp$SO4 <- as.numeric(rhiz_icp$SO4)
rhiz_icp$Mn <- as.numeric(rhiz_icp$Mn)

# match depths
# Change "34-44" to "30-40" for MCT2-4, env 2, 6/1/2018 & 6/10/2018
rhiz_icp$depth[rhiz_icp$depth == "34-44"] <- "30-40"

# Change "35-45" to "30-40" for MCT2-1, env rw, 6/1/2018 & 6/10/2018
rhiz_icp$depth[rhiz_icp$depth == "35-45"] <- "30-40"

# Change "63-73" to "60-70" for MCT2-4, env 2, 6/1/2018 & 6/10/2018
rhiz_icp$depth[rhiz_icp$depth == "63-73"] <- "60-70"

# Change "65-75" to "60-70" for MCT2-4, env 1, 6/1/2018 & 6/10/2018
rhiz_icp$depth[rhiz_icp$depth == "65-75"] <- "60-70"

# change depths to multiple columns
rhiz_icp$depth_class <- ifelse(rhiz_icp$depth == "0-10", "surface",
                                   ifelse(rhiz_icp$depth == "30-40", "30-40",
                                          ifelse(rhiz_icp$depth == "60-70", "60-80",
                                                 ifelse(rhiz_icp$depth == "70-80", "60-80",
                                                        ifelse(rhiz_icp$depth == "80-90", "80-100", "80-100")))))

rhiz_icp$depth_class <- factor(rhiz_icp$depth_class, levels = c("surface", "30-40", "60-80", "80-100"))


# Average by date/time & position/depth (averaging the reps rw + rd, 1 + 2, etc.)
rhiz_icp$year <- year(rhiz_icp$date)
rhiz_icp$month <- month(rhiz_icp$date)
rhiz_icp$day <- day(rhiz_icp$date)

rhiz_icp_av <- rhiz_icp %>%
  group_by(year, month, day, position_mct2, depth_class) %>%
  summarize(Fe_mean = mean(Fe, na.rm=TRUE),
            SO4_mean = mean(SO4, na.rm=TRUE),
            NO3_mean = mean(NO3, na.rm=TRUE),
            Mn_mean = mean(Mn, na.rm=TRUE)) %>%
  mutate(date = make_date(year, month, day))

# generate list of samples submitted to Patricia (take out rows with "x" for Cl)
rhiz_icp_submitted <- rhiz_icp[-grep("x", rhiz_icp$Cl), ]
#write.csv(rhiz_icp_submitted, file = "rhiz_icp_submitted.csv")

```

## Initial figures
```{r}
ggplot(subset(rhiz_icp)) +
  aes(x=date, y=Fe, color=depth_class) +
  geom_point() +
  ylab("Fe (M)") +
  facet_wrap(~position_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        strip.text.x = element_text(size = 20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank())

ggplot(rhiz_icp) +
  aes(x=date, y=SO4, color=depth_class) +
  geom_point() +
  ylab("SO4 (mM)") +
  facet_wrap(~position_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        strip.text.x = element_text(size = 20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank())

ggplot(subset(rhiz_icp)) +
  aes(x=date, y=NO3, color=depth_class) +
  geom_point() +
  ylab("NO3 (mM)") +
  facet_wrap(~position_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        strip.text.x = element_text(size = 20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank())
```


## Test merge with TOC
```{r}
merge <- merge(rhiz_icp, rhiz_toc)

# Change facet labels for Fe_mmol_g, fraction_fe2, C_mmol_g
position.labs <- c("MCT2-1", "MCT2-3")
names(position.labs) <- c(1, 3)

# Group early & late season (first 3 dates = "early", last 3 dates = "late")
merge$season_id <- ifelse(merge$date < "2018-07-01", "early", "late")

f <- ggplot(subset(merge, Fe < 4.677414e-06 & c_mm < 10 & depth_class %in% c("surface", "30-40") & position_mct2 %in% c(1,3))) +
  aes(x=Fe*1000*1000, y=c_mm, color=depth_class) +
  geom_point() + geom_smooth(method="lm") +
  xlab("Fe (uM)") + ylab("NPOC (mM)") +
  facet_wrap(~position_mct2+season_id, scales="free", labeller = labeller(position_mct2 = position.labs)) +
  theme_bw() +
  theme(strip.text.x = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.title=element_text(size=12),
        legend.text=element_text(size=12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_color_manual(name="Soil depth", breaks = c("surface", "30-40"), labels = c("5 cm", "30 cm"), values=c("#009E73", "#999999"))

f <- arrangeGrob(f) #generates f
ggsave(file="porewater_fe_c_2018.pdf", f, width = 5, height = 4, units = "in")


# Make sure dates line up; put date on bottom graph; make legends match (same titles, color, etc.)
lims_2018 <- as.POSIXct(strptime(c("2018-05-26 00:00:00", "2018-10-01 00:00:00"), format = "%Y-%m-%d %H:%M"))

# Name transect positions 1, 3, 4
position_names <- c(
                    "MCT2-1" = "1",
                    "MCT2-3" = "3",
                    "MCT2-4" = "4"
                    )

# Colorblind palette with grey:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


# Pore water NPOC 2018
f <- ggplot(subset(rhiz_toc_weighted_mean, weighted.value < 8 & position_mct2 %in% c(1,3) & depth_class %in% c("surface", "30-40", "60-80", "80-100"))) +
  aes(x=as.POSIXct(date), y=weighted.value, color=depth_class) +
  geom_point(size=2) + geom_line(size=1) +
  ylab("NPOC (mM)") +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~position_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlim(lims_2018) +
  scale_color_manual(name="Soil depth", breaks = c("surface", "30-40", "60-80", "80-100"), labels = c("5 cm", "30 cm", "70 cm", "100 cm"), values=c("#009E73", "#999999", "#E69F00", "#56B4E9"))

f <- arrangeGrob(f) #generates f
ggsave(file="porewater_npoc_2018.pdf", f, width = 6, height = 3, units = "in")


# Pore water Fe 2018
f <- ggplot(subset(merge, Fe < 4.677414e-06 & c_mm < 10 & position_mct2 %in% c(1,3))) +
  aes(x=date, y=Fe*1000*1000, color=depth_class) +
  geom_point(size=2) + geom_line(size=1) +
  ylab("Fe (uM)") +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~position_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlim(lims_2018) +
  scale_color_manual(name="Soil depth", breaks = c("surface", "30-40", "60-80", "80-100"), labels = c("5 cm", "30 cm", "70 cm", "100 cm"), values=c("#009E73", "#999999", "#E69F00", "#56B4E9"))

f <- arrangeGrob(f) #generates f
ggsave(file="porewater_fe_2018.pdf", f, width = 6, height = 3, units = "in")


```