---
title: "EastRiver_fticrms"
author: "CGA"
date: "July 20, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary packages
library(tidyverse)
library(readxl)
library(gridExtra)
library(lubridate)
library(reshape2)
library(ggpubr)
library(vegan)
library(viridis)
library(ggsci)
# Set working directory
setwd("~/east-river/")
```

## Load and tidy FT-ICR-MS data
```{r}
# Rachelle processed FT-ICR-MS data; see email for her R scripts.
#It gives you the abundance of peaks that can be assigned to different compound classes (lipids, carbs, …) and a few other metrics (S, N or P containing compounds, molecular weight, etc)

#For the poster, it might be a good starting point to simply average the three replicates and see if the means between the different depths/locations are different.  No stats necessary for now, but some visualization would be great.

icr <- read_excel("Data/CountOutput-Marco Solvent Extration SPE Report May 2018.xlsx", na="NA")

# Remove "NA" rows
icr <- icr[complete.cases(icr[,1]), ]

# Replace periods with underscores in "sample" column
icr$sample <- gsub("[.]","_", icr$sample) 

# Separate the "sample" column
icr <- icr %>%
  separate(sample, c("ID", "extract", "type"), "_")

# Remove "X" at beginning of ID
icr$ID <- sub("*X", "", icr$ID)

# Sum of "set #1" (columns lipids to tannins)
icr$set_1 <- rowSums(icr[, c(22:29)])

# Sum of "set #2" (columns aliphatics to lignin phenol)
icr$set_2 <- rowSums((icr[, c(31:36)]))

# Normalizing the number of peaks for each compound class (lipids, lignins, carbs, etc.) to the total number of peaks. Note that there are two different sets of compound classes that you should consider separately (called set_1 and set_2)


icr$Lipids_norm <- icr$Lipids / icr$set_1 * 10
icr$UnSaturated_Hydrocarbons_norm <- icr$UnSaturated_Hydrocarbons / icr$set_1 * 10
icr$Condensed_Hydrocarbons_norm <- icr$Condensed_Hydrocarbons / icr$set_1 * 10
icr$Proteins_norm <- icr$Proteins / icr$set_1 * 10
icr$Amino_Sugars_norm <- icr$Amino_Sugars / icr$set_1 * 10
icr$Carbohydrates_norm <- icr$Carbohydrates / icr$set_1 * 10
icr$Lignin_norm <- icr$Lignin / icr$set_1 * 10
icr$Tannins_norm <- icr$Tannins / icr$set_1 * 10
  
icr$Aliphatics_norm <- icr$Aliphatics / icr$set_2 * 10
icr$AliphaticsN_norm <- icr$AliphaticsN / icr$set_2 * 10
icr$Saturated_norm <- icr$Saturated / icr$set_2 * 10
icr$Condensed_Aromatics_norm <- icr$Condensed_Aromatics / icr$set_2 * 10
icr$Aromatic_norm <- icr$Aromatic / icr$set_2 * 10
icr$LigninPhenolics_norm <- icr$LigninPhenolics / icr$set_2 * 10


# Relative abundance of CHO, CHON, etc.; figure presented like FT-ICR compound classes figure.
# Sum of "CHO, CHON, etc"" (columns CHO to CHONSP)
icr$elements <- rowSums(icr[, c(13:20)])

# Normalizing the number of peaks for each element class (CHO, CHON, etc.) to the total number of peaks.
icr$CHO_norm <- icr$CHO / icr$elements
icr$CHON_norm <- icr$CHON / icr$elements
icr$CHOS_norm <- icr$CHOS / icr$elements
icr$CHOP_norm <- icr$CHOP / icr$elements
icr$CHONS_norm <- icr$CHONS / icr$elements
icr$CHONP_norm <- icr$CHONP / icr$elements
icr$CHOSP_norm <- icr$CHOSP / icr$elements
icr$CHONSP_norm <- icr$CHONSP / icr$elements

colnames(icr)

icr_norm <- icr[, c(1:12, 40:53, 55:62)]

```


## Merge with sample ID key (average triplicates?)
```{r}
sample_key <- read.csv("Data/June2017_EastRiver_samplekey.csv")

# Separate the "sample" column into two separate columns (location, rep)
sample_key <- sample_key %>%
  separate(sample, c("location", "rep"), "-")

# Separate the "depth_cm" column into two separate columns (top_cm, btm_cm)
sample_key <- sample_key %>%
  separate(depth_cm, c("top_cm", "btm_cm"), "-")

sample_key$top_cm <- as.numeric(sample_key$top_cm)
sample_key$btm_cm <- as.numeric(sample_key$btm_cm)
sample_key$depth_category <- ifelse(sample_key$top_cm < 40, "surface", ifelse(sample_key$top_cm > 90, "deep", "middle"))

icr_total_norm <- merge(icr_norm, sample_key, all.x=TRUE) #all.x=TRUE to keep blanks

# Average triplicates? (b1, b2, b3)
soils <- read.csv("Data/June2017_EastRiver_sample_list_with_depths.csv")
soils <- soils[ , c(1,4,5)]
colnames(soils)[2] <- "Location"
# Merge ICR and soils data, then average by location & depth_class
icr_total_merge <- merge(icr_total_norm, soils)

colnames(icr_total_merge)
#icr_total_merge <- icr_total_merge[, c(1:3,13:20,35:41)] #selecting only set 1 columns
icr_total_merge <- icr_total_merge[, c(1:3, 27:34,35:41)] #selecting only the CHO, etc. columns

# Melt the data
icr_melt <- melt(icr_total_merge, id=c("ID", "extract", "type", "top_cm", "btm_cm", "rep", "location", "Location", "Depth_cm", "depth_category"))

icr_melt$extract <- factor(icr_melt$extract, levels = c("Dith", "HCl", "PP", "H2O"))
icr_melt$location <- factor(icr_melt$location)

# Averages of ICR data
icr_melt_averages <- icr_melt %>%
  group_by(Location, Depth_cm, variable) %>%
  summarize(value.mean= mean(value), value.sd = sd(value))

```

## N and P compounds from ICR data
```{r}

## Edit sample key
## Depth categories
sample_key$depth_category <- ifelse(sample_key$top_cm < 40, "shallow", ifelse(sample_key$top_cm > 90, "deep", "subsurface"))

# Make "depth_category" a factor, and order the depth classes
sample_key$depth_category <- factor(sample_key$depth_category, levels = c("shallow", "subsurface", "deep"))
sample_key$location <- factor(sample_key$location)

## Plot N- and P-containing compounds from ICR data
elements_icr <- subset(icr_melt, variable %in% c("CHO","CHON","CHOS","CHOP","CHONS","CHONP","CHOSP","CHONSP"))

# N-containing compounds
n_icr <- elements_icr[grep("N", elements_icr$variable), ]

# P-containing compounds
p_icr <- elements_icr[grep("P", elements_icr$variable), ]

# Sum the N- and P-containing compounds
n_sum <- aggregate(value~ID+extract, n_icr, sum)
n_sum <- merge(n_sum, sample_key, all.x=TRUE)
n_sum$depth_category <- factor(n_sum$depth_category, levels = unique(n_sum$depth_category))

p_sum <- aggregate(value~ID+extract, p_icr, sum)
p_sum <- merge(p_sum, sample_key, all.x=TRUE)
p_sum$depth_category <- factor(p_sum$depth_category, levels = unique(p_sum$depth_category))


ggplot(subset(p_sum, depth_category %in% c("shallow", "subsurface"))) +
  aes(y=value, x=depth_category, fill=extract) +
  geom_bar(stat="identity") +
  coord_flip() +
  xlab("") + ylab("P-containing -ICR compounds") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_fill_discrete(name="Sequential extraction pool", breaks = c("H2O", "PP", "HCl", "Dith"), labels = c("Water", "Pyrophosphate", "HCl", "Dithionite")) +
  facet_grid(location~.)

ggplot(subset(n_sum, depth_category %in% c("shallow", "subsurface"))) +
  aes(y=value, x=depth_category, fill=extract) +
  geom_bar(stat="identity") +
  coord_flip() +
  xlab("") + ylab("N-containing -ICR compounds") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_fill_discrete(name="Sequential extraction pool", breaks = c("H2O", "PP", "HCl", "Dith"), labels = c("Water", "Pyrophosphate", "HCl", "Dithionite")) +
  facet_grid(location~.)

```

## NMDS using Vegan
```{r}
#Another idea would be to run a PCA or NMDS on the initial “raw” dataset. You could see to what extent the different extractions cluster, and if the different locations/depths cluster together or group separately. See fig. 3 in Graham et al. 

# cluster by extraction (H2O, PP, HCl, Dith)
icr_total <- icr[, c(1:37)]
icr_total <- merge(icr_total, sample_key, all.x=TRUE) #all.x=TRUE to keep blanks

icr_total <- icr_total %>%
  unite(ID_extract, ID, extract, sep="_", remove=FALSE)

# change ID to rownames
icr_total <- icr_total %>% 
  remove_rownames %>% 
  column_to_rownames(var="ID_extract")

colnames(icr_total)

icr_nmds <- icr_total[, c(13:25, 27:36)]
icr_metatable <- icr_total[, c(1,2,42)]
icr_metatable <- icr_metatable[rownames(icr_nmds),]


#http://geoffreyzahn.com/nmds-example/
fticr_dist <- as.matrix((vegdist(icr_nmds, "bray")))

NMDS <- metaMDS(fticr_dist)

# Build a data frame with NMDS coordinates and metadata
MDS1 <- NMDS$points[,1]
MDS2 <- NMDS$points[,2]
NMDS <- data.frame(MDS1 = MDS1, MDS2 = MDS2, Extract = icr_metatable$extract, Depth = icr_metatable$depth_category)

ggplot(NMDS) +
  stat_ellipse(aes(x=MDS1, y=MDS2, col=Extract)) +
  geom_point(aes(x=MDS1, y=MDS2, col=Extract, shape=Depth)) +
  theme_bw() +
  ggtitle("NMDS, East River FT-ICR-MS")

p1 <- ggplot(subset(NMDS, Depth %in% "surface")) +
  aes(x=MDS1, y=MDS2, col=Extract) +
  geom_point() +
  stat_ellipse() +
  theme_bw() +
  ggtitle("surface soils")

p2 <- ggplot(subset(NMDS, Depth %in% "middle")) +
  aes(x=MDS1, y=MDS2, col=Extract) +
  geom_point() +
  stat_ellipse() +
  theme_bw() +
  ggtitle("subsurface soils")

#Plot together with shared legend
ggarrange(p1, p2, ncol=1, nrow=2, common.legend = TRUE, legend="right")

```

## Plots
```{r}
ggplot(icr_total) +
  aes(x=top_cm, y=Condensed_Aromatics, color=location) +
  geom_point() +
  facet_wrap(~extract, scales="free")

# Melted data
ggplot(subset(icr_melt, extract %in% "H2O")) +
  aes(x=top_cm, y=value) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~variable, scales="free") +
  ggtitle("Water-extractable carbon")

ggplot(subset(icr_melt, extract %in% "PP")) +
  aes(x=top_cm, y=value) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~variable, scales="free") +
  ggtitle("Pyrophosphate-extractable carbon")

ggplot(subset(icr_melt, extract %in% "HCl")) +
  aes(x=top_cm, y=value) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~variable, scales="free") +
  ggtitle("HCl-extractable carbon")

ggplot(subset(icr_melt, extract %in% "Dith")) +
  aes(x=top_cm, y=value) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~variable, scales="free") +
  ggtitle("Dithionite-extractable carbon")

# Bar plots for relative distribution, "set 1"
ggplot(subset(icr_melt, extract %in% "H2O" & depth_category %in% c("surface", "middle") & variable %in% c("Lipids_norm", "UnSaturated_Hydrocarbons_norm", "Condensed_Hydrocarbons_norm", "Proteins_norm", "Amino_Sugars_norm", "Carbohydrates_norm", "Lignin_norm", "Tannins_norm"))) +
  aes(x="", y = value, fill = variable) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) + 
  facet_wrap(~depth_category) +
  ggtitle("Water-extractable carbon (set 1)") +
  scale_fill_discrete(name="Compound class")

ggplot(subset(icr_melt, extract %in% "PP" & depth_category %in% c("surface", "middle") & variable %in% c("Lipids_norm", "UnSaturated_Hydrocarbons_norm", "Condensed_Hydrocarbons_norm", "Proteins_norm", "Amino_Sugars_norm", "Carbohydrates_norm", "Lignin_norm", "Tannins_norm"))) +
  aes(x="", y = value, fill = variable) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) + 
  facet_wrap(~depth_category) +
  ggtitle("Pyrophosphate-extractable carbon (set 1)") +
  scale_fill_discrete(name="Compound class")

ggplot(subset(icr_melt, extract %in% "HCl" & depth_category %in% c("surface", "middle") & variable %in% c("Lipids_norm", "UnSaturated_Hydrocarbons_norm", "Condensed_Hydrocarbons_norm", "Proteins_norm", "Amino_Sugars_norm", "Carbohydrates_norm", "Lignin_norm", "Tannins_norm"))) +
  aes(x="", y = value, fill = variable) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) + 
  facet_wrap(~depth_category) +
  ggtitle("HCl-extractable carbon (set 1)") +
  scale_fill_discrete(name="Compound class")

ggplot(subset(icr_melt, extract %in% "Dith" & depth_category %in% c("surface", "middle") & variable %in% c("Lipids_norm", "UnSaturated_Hydrocarbons_norm", "Condensed_Hydrocarbons_norm", "Proteins_norm", "Amino_Sugars_norm", "Carbohydrates_norm", "Lignin_norm", "Tannins_norm"))) +
  aes(x="", y = value, fill = variable) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) + 
  facet_wrap(~depth_category) +
  ggtitle("Dithionite-extractable carbon (set 1)") +
  scale_fill_discrete(name="Compound class")

# Bar plots for relative distribution, "set 2"
ggplot(subset(icr_melt, extract %in% "H2O" & depth_category %in% c("surface", "middle") & variable %in% c("Aliphatics_norm", "AliphaticsN_norm", "Saturated_norm", "Condensed_Aromatics_norm", "Aromatic_norm", "LigninPhenolics_norm"))) +
  aes(x="", y = value, fill = variable) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) + 
  facet_wrap(~depth_category) +
  ggtitle("Water-extractable carbon (set 2)") +
  scale_fill_discrete(name="Compound class")

# Change labels of sequential extractions
icr_melt$extraction2 <- factor(icr_melt$extract, levels = c("Dith", "HCl", "PP", "H2O"))
levels(icr_melt$extraction2) <- c("Dithionite",  "HCl", "Pyrophosphate", "Water")

# Levels for either set 1 or CHO
#levels(icr_melt$variable) <- c("Lipids_norm", "Amino_Sugars_norm", "Proteins_norm", "UnSaturated_Hydrocarbons_norm", "Condensed_Hydrocarbons_norm", "Carbohydrates_norm", "Lignin_norm", "Tannins_norm")

icr_melt$variable <- factor(icr_melt$variable,
                            levels = rev(c("CHO_norm", "CHON_norm", "CHOS_norm", "CHOP_norm", "CHONS_norm", "CHONP_norm", "CHOSP_norm", "CHONSP_norm")))

# Stacked bar plots
cbPalette <- viridis(8)
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


g1 <- ggplot(subset(icr_melt, depth_category %in% "surface" & variable %in% c("Lipids_norm", "UnSaturated_Hydrocarbons_norm", "Condensed_Hydrocarbons_norm", "Proteins_norm", "Amino_Sugars_norm", "Carbohydrates_norm", "Lignin_norm", "Tannins_norm"))) +
  aes(y=value/100, x=extraction2, fill=variable) +
  geom_bar(stat="identity") +
  coord_flip() +
  xlab("Shallow") + ylab("") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 35),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title=element_text(size=30),
        legend.text=element_text(size=30),
        axis.text.y = element_text(angle = 60, vjust = 0.5, hjust=0.85)) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_igv(name="Compound class",
                      breaks=rev(c("Lipids_norm", "Amino_Sugars_norm", "Proteins_norm", "UnSaturated_Hydrocarbons_norm", "Condensed_Hydrocarbons_norm", "Carbohydrates_norm", "Lignin_norm", "Tannins_norm")),
                      labels=rev(c("Lipids", "Amino Sugars", "Proteins", "Unsaturated Hydrocarbons", "Condensed Hydrocarbons", "Carbohydrates", "Lignin", "Tannins")))
g1


g2 <- ggplot(subset(icr_melt, depth_category %in% "middle" & variable %in% c("Lipids_norm", "UnSaturated_Hydrocarbons_norm", "Condensed_Hydrocarbons_norm", "Proteins_norm", "Amino_Sugars_norm", "Carbohydrates_norm", "Lignin_norm", "Tannins_norm"))) +
  aes(y=value/100, x=extraction2, fill=variable) +
  geom_bar(stat="identity") +
  coord_flip() +
  xlab("Subsurface") + ylab("") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 35),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title=element_text(size=30),
        legend.text=element_text(size=30),
        axis.text.y = element_text(angle = 60, vjust = 0.5, hjust=0.85)) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_igv(name="Compound class",
                      breaks=rev(c("Lipids_norm", "Amino_Sugars_norm", "Proteins_norm", "UnSaturated_Hydrocarbons_norm", "Condensed_Hydrocarbons_norm", "Carbohydrates_norm", "Lignin_norm", "Tannins_norm")),
                      labels=rev(c("Lipids", "Amino Sugars", "Proteins", "Unsaturated Hydrocarbons", "Condensed Hydrocarbons", "Carbohydrates", "Lignin", "Tannins")))
g2

#Plot together with shared legend
ggarrange(g1, g2, ncol=1, nrow=2, common.legend = TRUE, legend="right")


# Stacked bar plots of relative distribution of CHO, CHON, etc.
e1 <- ggplot(subset(icr_melt, depth_category %in% "surface" & variable %in% c("CHO_norm", "CHON_norm", "CHOS_norm", "CHOP_norm", "CHONS_norm", "CHONP_norm", "CHOSP_norm", "CHONSP_norm"))) +
  aes(y=value/10, x=extraction2, fill=variable) +
  geom_bar(stat="identity") +
  coord_flip() +
  xlab("Shallow") + ylab("") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 35),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title=element_text(size=30),
        legend.text=element_text(size=30),
        axis.text.y = element_text(angle = 60, vjust = 0.5, hjust=0.85)) +
    scale_y_continuous(labels = scales::percent) +
   scale_fill_igv(name="",
                  breaks=(c("CHO_norm", "CHON_norm", "CHOS_norm", "CHOP_norm", "CHONS_norm", "CHONP_norm", "CHOSP_norm", "CHONSP_norm")),
                  labels=(c("CHO", "CHON", "CHOS", "CHOP", "CHONS", "CHONP", "CHOSP", "CHONSP")))
e1

e2 <- ggplot(subset(icr_melt, depth_category %in% "deep" & variable %in% c("CHO_norm", "CHON_norm", "CHOS_norm", "CHOP_norm", "CHONS_norm", "CHONP_norm", "CHOSP_norm", "CHONSP_norm"))) +
  aes(y=(value/10)*3, x=extraction2, fill=variable) +
  geom_bar(stat="identity") +
  coord_flip() +
  xlab("Subsurface") + ylab("") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 35),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title=element_text(size=30),
        legend.text=element_text(size=30),
        axis.text.y = element_text(angle = 60, vjust = 0.5, hjust=0.85)) +
    scale_y_continuous(labels = scales::percent) +
   scale_fill_igv(name="",
                  breaks=(c("CHO_norm", "CHON_norm", "CHOS_norm", "CHOP_norm", "CHONS_norm", "CHONP_norm", "CHOSP_norm", "CHONSP_norm")),
                  labels=(c("CHO", "CHON", "CHOS", "CHOP", "CHONS", "CHONP", "CHOSP", "CHONSP")))
e2

#Plot together with shared legend
ggarrange(e1, e2, ncol=1, nrow=2, common.legend = TRUE, legend="right")

```
