---
title: "EastRiver_TOC"
author: "CGA"
date: "May 11, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary packages
library(tidyverse)
library(readxl)
library(gridExtra)
library(scales)
```

## TOTAL ORGANIC CARBON
## Load files with TOC data, rbind, and tidy
```{r}
TOC_1 <- read.table("Data/TOC/11May2018_EastRiver_TOC_H2O_HCl_means.txt", skip=11, fill=TRUE)[ , c(3,5)]
TOC_2 <- read.table("Data/TOC/12May2018_EastRiver_TOC_dith_pp_means.txt", skip=11, fill=TRUE)[ , c(4,5)]

# Label columns
colnames(TOC_1) <- c("sample","c_ppm")
colnames(TOC_2) <- c("sample","c_ppm")

# Row-bind TOC_1 and TOC_2
TOC <- rbind(TOC_1, TOC_2)

# If blanks and standard checks look ok, take them out
TOC_samples <- TOC[grep("x", TOC$sample), ]
TOC_samples$c_ppm <- as.numeric(TOC_samples$c_ppm)

# Separate the sample column
TOC_samples <- TOC_samples %>%
  separate(sample, c("ID", "extraction", "dilution_toc"), "-")

# Correct sample concentrations with correct standard curve (I made 1000 ppm KHP, which is actually 470 mg C / L when corrected for 47% C in KHP by mass)
# To do this, multiply concentrations by 0.47
TOC_samples$c_ppm_corrected <- TOC_samples$c_ppm * 0.47

```

## Merge with MP-ICP-AES data
```{r}
mp <- read.csv("Data/0.processed_data/seq_extraction_2017_mp-aes_processed.csv")
cn <- read.csv("Data/0.processed_data/EA_bulk_dens-fractions_CN_2017_processed.csv")

toc_mp <- merge(TOC_samples, mp, by=c("ID", "extraction"))

```

## Correct TOC data
```{r}

# 10x dilution for pyrophosphate, 2x dilution for all others
#Need to report C in mol C g-1 soil, so you will want to multiply the initial value (mg L-1) by (volume of extractant in L/mass of soil in g). The resulting number is then divided by 12 mg mmol-1 (or g mol-1).
toc_mp$mmol_c_g[toc_mp$extraction=="pp"] <- 
  (toc_mp$c_ppm[toc_mp$extraction=="pp"] * 10) * (0.01/0.33) * (1/12)

toc_mp$mmol_c_g[toc_mp$extraction=="dith"] <- 
  (toc_mp$c_ppm[toc_mp$extraction=="dith"] * 2) * (0.01/0.33) * (1/12)

toc_mp$mmol_c_g[toc_mp$extraction=="hcl"] <- 
  (toc_mp$c_ppm[toc_mp$extraction=="hcl"] * 2) * (0.01/0.33) * (1/12)

toc_mp$mmol_c_g[toc_mp$extraction=="h2o"] <- 
  (toc_mp$c_ppm[toc_mp$extraction=="h2o"] * 2) * (0.01/0.33) * (1/12)

toc_mp$extraction <- factor(toc_mp$extraction, levels = c("dith", "hcl", "pp", "h2o"))
toc_mp$depth_category <- factor(toc_mp$depth_category, levels = unique(toc_mp$depth_category))
toc_mp$extraction2 <- factor(toc_mp$extraction, levels = c("h2o", "pp", "hcl", "dith"))

```

## TOTAL NITROGEN
## Load files with TN data, rbind, and tidy
```{r}
TN_1 <- read.table("Data/TOC/13May2018_EastRiver_TN_H2O_HCl_means.txt", skip=11, fill=TRUE)[ , c(4,5)]
TN_2 <- read.table("Data/TOC/14May2018_EastRiver_TN_dith_pp_means.txt", skip=11, fill=TRUE)[ , c(4,5)]

# Label columns
colnames(TN_1) <- c("sample","n_ppm")
colnames(TN_2) <- c("sample","n_ppm")

# Row-bind TN_1 and TN_2
TN <- rbind(TN_1, TN_2)

# If blanks and standard checks look ok, take them out
TN_samples <- TN[grep("x", TN$sample), ]
TN_samples$n_ppm <- as.numeric(as.character(TN_samples$n_ppm))

# Separate the sample column
TN_samples <- TN_samples %>%
  separate(sample, c("ID", "extraction", "dilution_tn"), "-")

TN_samples$extraction <- factor(TN_samples$extraction, levels = c("h2o", "pp", "hcl", "dith"))
#levels(TN_samples$extraction) <- c("Water", "Pyrophosphate", "HCl", "Dithionite")


# Correct sample concentrations with correct standard curve (I made 1000 ppm KNO3, which is actually 138.5 mg N / L when corrected for 13.85% N in KNO3 by mass)
# To do this, multiply concentrations by 0.1385
TN_samples$n_ppm_corrected <- TN_samples$n_ppm * 0.1385


# Correct for soil weights, dilution (10x for pyrophosphate, 2x for all others), convert to mmol TN L-1
#(x TN)(mg L-1)*(1/14.0067) ((mmol mg-1)-1) = x mmol TN L-1
TN_samples$mmol_n_g[TN_samples$extraction=="pp"] <- 
  (TN_samples$n_ppm_corrected[TN_samples$extraction=="pp"] * 10) * (0.01/0.33) * (1/14.0067)

TN_samples$mmol_n_g[TN_samples$extraction=="dith"] <- 
  (TN_samples$n_ppm_corrected[TN_samples$extraction=="dith"] * 2) * (0.01/0.33) * (1/14.0067)

TN_samples$mmol_n_g[TN_samples$extraction=="hcl"] <- 
  (TN_samples$n_ppm_corrected[TN_samples$extraction=="hcl"] * 2) * (0.01/0.33) * (1/14.0067)

TN_samples$mmol_n_g[TN_samples$extraction=="h2o"] <- 
  (TN_samples$n_ppm_corrected[TN_samples$extraction=="h2o"] * 2) * (0.01/0.33) * (1/14.0067)

# Merge with TOC/MP data
toc_tn_mp <- merge(TN_samples, toc_mp, by=c("ID", "extraction"))

# Save as csv
#write.csv(toc_tn_mp, "Data/0.processed_data/seq_extraction_2017_toc-tn-mp_processed.csv")

```

## TOC & metal figures
```{r}
# TOC figures (amount per depth across transect)
ggplot(subset(toc_mp, element %in% "Fe" & depth_category %in% c("shallow", "subsurface"))) +
  aes(x=depth_category, y=mmol_c_g, fill=extraction) +
  geom_bar(stat="identity") +
  coord_flip() +
  xlab("") + ylab(expression(Organic~Carbon~(mmol~g^-1))) +
  theme_bw() +
  theme(axis.text = element_text(size = 30),
        axis.title = element_text(size = 35),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.y = element_text(size = 35),
        legend.title=element_text(size=27),
        legend.text=element_text(size=27),
        legend.position = 'top', 
        legend.spacing = unit(16, 'pt')) +
  scale_fill_manual(name="", breaks = c("h2o", "pp", "hcl", "dith"), labels = c("Water", "Pyrophosphate", "HCl", "Dithionite"), values=rev(c("#0072B2", "#F0E442", "#000000", "#009E73"))) +
  facet_grid(location~.)

# TOC vs. metals
ggplot(subset(toc_mp, element %in% "Fe")) +
  aes(x=top_cm, y=mmol_c_g) +
  geom_point() +
  facet_wrap(~extraction, scales="free") +
  xlab("soil depth (cm)") + ylab("TOC (mmol C g-1)")

levels(toc_mp$extraction2) <- c("Water", "Pyrophosphate", "HCl", "Dithionite")

ggplot(subset(toc_mp, element %in% "Fe")) +
  aes(x=conc_corrected_mmol_g, y=mmol_c_g) +
  geom_point(aes(color=location, size=3)) + geom_smooth(method="lm") +
  facet_wrap(~extraction2, scales="free") +
  xlab(expression(Iron~(mmol~g^-1))) + ylab(expression(Organic~Carbon~(mmol~g^-1))) +
  labs(color= "Location") +
  theme_bw() +
  theme(axis.text = element_text(size = 18),
        axis.title = element_text(size = 35),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 35),
        legend.title=element_text(size=30),
        legend.text=element_text(size=30),
        legend.key.size = unit(3,"point")) +
  scale_size_continuous(guide=FALSE) +
  guides(color = guide_legend(override.aes = list(size=5)))

# R2 and p-values for TOC vs. Fe correlations (by extraction)
fe_toc_water <- subset(toc_mp, element %in% "Fe" & extraction %in% "h2o")
fe_toc_pp <- subset(toc_mp, element %in% "Fe" & extraction %in% "pp")
fe_toc_hcl <- subset(toc_mp, element %in% "Fe" & extraction %in% "hcl")
fe_toc_dith <- subset(toc_mp, element %in% "Fe" & extraction %in% "dith")

# Water
plot(fe_toc_water$conc_corrected_mmol_g, fe_toc_water$mmol_c_g)
fe_water_model <- lm(mmol_c_g ~ conc_corrected_mmol_g, data=fe_toc_water)
abline(fe_water_model, col = "red")
summary(fe_water_model)

# Pyrophosphate
plot(fe_toc_pp$conc_corrected_mmol_g, fe_toc_pp$mmol_c_g)
fe_pp_model <- lm(mmol_c_g ~ conc_corrected_mmol_g, data=fe_toc_pp)
abline(fe_pp_model, col = "red")
summary(fe_pp_model)

# HCl
plot(fe_toc_hcl$conc_corrected_mmol_g, fe_toc_hcl$mmol_c_g)
fe_hcl_model <- lm(mmol_c_g ~ conc_corrected_mmol_g, data=fe_toc_hcl)
abline(fe_hcl_model, col = "red")
summary(fe_hcl_model)

# Dithionite
plot(fe_toc_dith$conc_corrected_mmol_g, fe_toc_dith$mmol_c_g)
fe_dith_model <- lm(mmol_c_g ~ conc_corrected_mmol_g, data=fe_toc_dith)
abline(fe_dith_model, col = "red")
summary(fe_dith_model)



## Nitrogen figures

ggplot(subset(toc_tn_mp, element %in% "Al")) +
  aes(x=top_cm, y=n_ppm) +
  geom_point() +
  facet_wrap(~extraction, scales="free") +
  xlab("soil depth (cm)") + ylab("TN (ppm)")

ggplot(subset(toc_tn_mp, element %in% "Al")) +
  aes(x=conc_corrected_mmol_g, y=n_ppm) +
  geom_point() +
  facet_wrap(~extraction, scales="free")

ggplot(toc_tn_mp) +
  aes(x=conc_corrected_mmol_g, y=n_ppm, color=top_cm) +
  geom_point() +
  facet_wrap(~extraction+element, scales="free") +
  xlab("element concentration (ppm)") + ylab("TN (ppm)")

ggplot(toc_tn_mp) +
  aes(x=c_ppm, y=n_ppm) +
  geom_point() +
  facet_wrap(~extraction, scales="free")

```

## TOC on 2018 East River sequential extractions (performed Fall 2019)
```{r}
toc_2018_1 <- read.table("Data/TOC/2019_11_19_001_EastRiver_hamine2x_cga.txt", skip=11, fill=TRUE)[ , c(3,5)]
toc_2018_2 <- read.table("Data/TOC/2019_11_20_001_EastRiver_hamine2x_cga_RUN.txt", skip=11, fill=TRUE)[ , c(3,5)]
toc_2018_3 <- read.table("Data/TOC/2019_11_21_001_hamine2x_cga.txt", skip=11, fill=TRUE)[, c(3,5)]
toc_2018_4 <- read.table("Data/TOC/2019_12_20_001_dith2x_cga.txt", skip=11, fill=TRUE)[, c(3,5)]
toc_2018_5 <- read.table("Data/TOC/2019_12_21_001_dith2x_cga.txt", skip=11, fill=TRUE)[, c(3,5)]

# Label columns
colnames(toc_2018_1) <- c("sample","c_ppm")
colnames(toc_2018_2) <- c("sample","c_ppm")
colnames(toc_2018_3) <- c("sample","c_ppm")
colnames(toc_2018_4) <- c("sample","c_ppm")
colnames(toc_2018_5) <- c("sample","c_ppm")


# Row-bind the TOC files
toc2018 <- rbind(toc_2018_1, toc_2018_2, toc_2018_3, toc_2018_4, toc_2018_5)

# If blanks and standard checks look ok, take them out
toc2018_samples <- toc2018[grep("x", toc2018$sample), ]
toc2018_samples$c_ppm <- as.numeric(toc2018_samples$c_ppm)

# Separate the sample column
toc2018_samples <- toc2018_samples %>%
  separate(sample, c("extraction", "dilution_toc", "id"), "_")
toc2018_samples <- toc2018_samples[,c(1,3,4)]
toc2018_samples$id <- as.numeric(toc2018_samples$id)

```

## Merge with MP-ICP-AES data and ferrozine data
```{r}
# In future, load processed scripts (for now run both TOC & MP-ICP-AES scripts to get dataframes)

toc_mp_2018 <- merge(toc2018_samples, mp_total2018, by=c("id", "extraction"))

# and merged with ferrozine data (need to figure out why so many data points are)
toc_mp_2018 <- merge(toc_mp_2018, ferro_wide_short)

```

## Correct TOC data
```{r}

# 10x dilution for pyrophosphate, 2x dilution for all others
#Need to report C in mol C g-1 soil, so you will want to multiply the initial value (mg L-1) by (volume of extractant in L/mass of soil in g). The resulting number is then divided by 12 mg mmol-1 (or g mol-1).
toc_mp_2018$mmol_c_g[toc_mp_2018$extraction=="pp"] <- 
  (toc_mp_2018$c_ppm[toc_mp_2018$extraction=="pp"] * 10) * (0.03/1) * (1/12)

toc_mp_2018$mmol_c_g[toc_mp_2018$extraction=="dith"] <- 
  (toc_mp_2018$c_ppm[toc_mp_2018$extraction=="dith"] * 2) * (0.03/1) * (1/12)

toc_mp_2018$mmol_c_g[toc_mp_2018$extraction=="ham"] <- 
  (toc_mp_2018$c_ppm[toc_mp_2018$extraction=="ham"] * 2) * (0.03/1) * (1/12)

toc_mp_2018$mmol_c_g[toc_mp_2018$extraction=="h2o"] <- 
  (toc_mp_2018$c_ppm[toc_mp_2018$extraction=="h2o"] * 2) * (0.03/1) * (1/12)

toc_mp_2018$extraction <- factor(toc_mp_2018$extraction, levels = c("dith", "ham", "pp", "h2o"))
toc_mp_2018$depth_category <- factor(toc_mp_2018$depth_category, levels = unique(toc_mp_2018$depth_category))
toc_mp_2018$extraction2 <- factor(toc_mp_2018$extraction, levels = c("h2o", "pp", "ham", "dith"))

levels(toc_mp_2018$extraction2) <- c("Water", "Pyrophosphate", "H-amine", "Dithionite")

# Group early & late season (first 3 dates = "early", last 3 dates = "late")
toc_mp_2018$season_id <- ifelse(toc_mp_2018$date < "2018-07-01", "early", "late")

```

## TOC & metal figures
```{r}
# TOC figures (amount per depth across transect)
ggplot(subset(toc_mp_2018, element %in% "Fe" & depth_category %in% c("shallow", "subsurface"))) +
  aes(x=depth_category, y=mmol_c_g, fill=extraction) +
  geom_bar(stat="identity") +
  coord_flip() +
  xlab("") + ylab(expression(Organic~Carbon~(mmol~g^-1))) +
  theme_bw() +
  theme(axis.text = element_text(size = 30),
        axis.title = element_text(size = 35),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.y = element_text(size = 35),
        legend.title=element_text(size=27),
        legend.text=element_text(size=27),
        legend.position = 'top', 
        legend.spacing = unit(16, 'pt')) +
  scale_fill_manual(name="", breaks = c("h2o", "pp", "ham", "dith"), labels = c("Water", "Pyrophosphate", "H-amine", "Dithionite"), values=rev(c("#0072B2", "#F0E442", "#000000", "#009E73"))) +
  facet_grid(location~.)

# TOC over time, by extraction
ggplot(subset(toc_mp_2018, element %in% "Fe")) +
  aes(x=date, y=mmol_c_g, color=depth_category2) +
  geom_point() +
  facet_wrap(~extraction+location)

# TOC by depth
ggplot(subset(toc_mp_2018, element %in% "Fe")) +
  aes(x=top_cm, y=mmol_c_g) +
  geom_point() +
  facet_wrap(~extraction, scales="free") +
  xlab("soil depth (cm)") + ylab("TOC (mmol C g-1)")

# TOC vs. metals
ggplot(subset(toc_mp_2018, element %in% "Fe")) +
  aes(x=conc_corrected_mmol_g, y=mmol_c_g) +
  geom_point(aes(color=depth_category2)) + geom_smooth(method="lm") +
  facet_wrap(~extraction2+date) +
  xlab(expression(Iron~(mmol~g^-1))) + ylab(expression(Organic~Carbon~(mmol~g^-1))) +
  labs(color= "Depth") +
  theme_bw() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 10),
        legend.title=element_text(size=10),
        legend.text=element_text(size=10),
        legend.key.size = unit(3,"point")) +
  scale_size_continuous(guide=FALSE) +
  guides(color = guide_legend(override.aes = list(size=1)))

ggplot(subset(toc_mp_2018, element %in% "Fe")) +
  aes(x=conc_corrected_mmol_g, y=mmol_c_g) +
  geom_point(aes(color=depth_category2)) + geom_smooth(method="lm") +
  facet_wrap(~extraction2+location) +
  xlab(expression(Iron~(mmol~g^-1))) + ylab(expression(Organic~Carbon~(mmol~g^-1))) +
  labs(color= "Depth") +
  theme_bw() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 10),
        legend.title=element_text(size=10),
        legend.text=element_text(size=10),
        legend.key.size = unit(3,"point")) +
  scale_size_continuous(guide=FALSE) +
  guides(color = guide_legend(override.aes = list(size=1)))

ggplot(subset(toc_mp_2018, element %in% "Fe" & depth_category %in% "shallow")) +
  aes(x=conc_corrected_mmol_g, y=mmol_c_g, color=location) +
  geom_point() + geom_smooth(method="lm") +
  facet_grid(~extraction2+season_id, scales="free") +
  xlab(expression(Iron~(mmol~g^-1))) + ylab(expression(Organic~Carbon~(mmol~g^-1))) +
  labs(color= "Depth") +
  theme_bw() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 10),
        legend.title=element_text(size=10),
        legend.text=element_text(size=10),
        legend.key.size = unit(3,"point")) +
  scale_size_continuous(guide=FALSE) +
  guides(color = guide_legend(override.aes = list(size=1)))

ggplot(subset(toc_mp_2018, element %in% "Fe" & depth_category %in% c("subsurface", "deep"))) +
  aes(x=conc_corrected_mmol_g, y=mmol_c_g, color=location) +
  geom_point() + geom_smooth(method="lm") +
  facet_grid(~extraction2+season_id, scales="free") +
  xlab(expression(Iron~(mmol~g^-1))) + ylab(expression(Organic~Carbon~(mmol~g^-1))) +
  labs(color= "Depth") +
  theme_bw() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 10),
        legend.title=element_text(size=10),
        legend.text=element_text(size=10),
        legend.key.size = unit(3,"point")) +
  scale_size_continuous(guide=FALSE) +
  guides(color = guide_legend(override.aes = list(size=1)))

ggplot(subset(toc_mp_2018, element %in% "Fe" & depth_category %in% c("shallow"))) +
  aes(x=conc_corrected_mmol_g, y=mmol_c_g) +
  geom_point(aes(color=location)) + geom_smooth(method="lm") +
  facet_wrap(~extraction2+date) +
  xlab(expression(Iron~(mmol~g^-1))) + ylab(expression(Organic~Carbon~(mmol~g^-1))) +
  labs(color= "Location") +
  theme_bw() +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 10),
        legend.title=element_text(size=10),
        legend.text=element_text(size=10),
        legend.key.size = unit(3,"point")) +
  scale_size_continuous(guide=FALSE) +
  guides(color = guide_legend(override.aes = list(size=1)))
```

## Figures for AGU 2019
```{r}
# Melt
colnames(toc_mp_2018)
# when not merging with ferrzone:
#toc_mp_2018_short <- toc_mp_2018[,c(1,2,5,8,9,11,12,13,15:20)]

# when merging with ferrozine:
toc_mp_2018_short <- toc_mp_2018[,c(1,2,4,6:19)]
colnames(toc_mp_2018_short)

tocmp_melt2018 <- melt(toc_mp_2018_short, id=c("id", "date", "location", "extraction", "element", "top_cm", "btm_cm", "depth_category", "depth_category2", "extraction2", "season_id"))

tocmp_melt2018$extraction <- factor(tocmp_melt2018$extraction, levels = c("dith", "ham", "pp", "h2o"))
tocmp_melt2018$depth_category <- factor(tocmp_melt2018$depth_category, levels = unique(tocmp_melt2018$depth_category))
tocmp_melt2018$depth_category2 <- factor(tocmp_melt2018$depth_category2, levels = unique(tocmp_melt2018$depth_category2))
tocmp_melt2018$location <- factor(tocmp_melt2018$location)
tocmp_melt2018$date <- as.Date(tocmp_melt2018$date, format="%m/%d/%Y")


# Change facet labels for Fe_mmol_g, fraction_fe2, C_mmol_g
extraction.labs <- c("Fe (mmol / g)", "C (mmol / g)", "Fe(II) / total Fe")
names(extraction.labs) <- c("conc_corrected_mmol_g", "mmol_c_g", "fraction_fe2_per_fe_total")

# Change order of facets
tocmp_melt2018$variable <- factor(tocmp_melt2018$variable,
                                  levels=c("conc_corrected_mmol_g","mmol_c_g","fraction_fe2_per_fe_total"))

# Change depth_category2 into actual numbers
depth.labs <- c("5-15", "30-40", "70-80", "100-110")
names(depth.labs) <- c("surface", "shallow", "subsurface", "deep")

# Calc weighted mean
colnames(tocmp_melt2018)
tocmp_melt2018_weighted <- tocmp_melt2018 %>% 
  group_by(date, location, extraction, element, depth_category2, season_id, variable) %>%
  mutate(weighted.value = weighted.mean(value, weights = importance))

# Colorblind palettes
# The palette with grey:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
# The palette with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# C & total Fe over time (weighted averages)
f <- ggplot(subset(tocmp_melt2018_weighted, element %in% "Fe" & variable %in% c("conc_corrected_mmol_g", "mmol_c_g"))) +
  aes(x=date, y=weighted.value, color=depth_category2) +
  geom_point() + geom_line() +
  facet_wrap(~location+variable, scales = "free", labeller = labeller(variable = extraction.labs)) +
#  labs(color= "Soil depth (cm)") +
  theme_bw() +
  theme(strip.text.x = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 12),
        axis.title = element_blank(),
        legend.title=element_text(size=12),
        legend.text=element_text(size=12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_color_manual(name="Soil depth", breaks = c("surface", "shallow", "subsurface", "deep"), labels = c("5 cm", "30 cm", "70 cm", "100 cm"), values=c("#009E73", "#999999", "#E69F00", "#56B4E9"))

f <- arrangeGrob(f) #generates f
ggsave(file="c_fe_weighted_2018.pdf", f, width = 7, height = 6, units = "in")


# C over time (weighted averages)
f <- ggplot(subset(tocmp_melt2018_weighted, element %in% "Fe" & variable %in% c("mmol_c_g"))) +
  aes(x=date, y=weighted.value, color=depth_category2) +
  geom_point() + geom_line() +
  facet_grid(rows = vars(location), scales = "free") +
  theme_bw() +
  theme(strip.text.y = element_blank(),
        axis.text = element_text(size = 12),
        axis.title = element_blank(),
        legend.title=element_text(size=12),
        legend.text=element_text(size=12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  scale_color_manual(name="Soil depth", breaks = c("surface", "shallow", "subsurface", "deep"), labels = c("5 cm", "30 cm", "70 cm", "100 cm"), values=c("#009E73", "#999999", "#E69F00", "#56B4E9"))

f <- arrangeGrob(f) #generates f
ggsave(file="c_weighted_2018.pdf", f, width = 3, height = 3, units = "in")

# Fe over time (weighted averages)
f <- ggplot(subset(tocmp_melt2018_weighted, element %in% "Fe" & variable %in% c("conc_corrected_mmol_g"))) +
  aes(x=date, y=weighted.value, color=depth_category2) +
  geom_point() + geom_line() +
  facet_grid(rows = vars(location), scales = "free") +
  theme_bw() +
  theme(strip.text.y = element_blank(),
        axis.text = element_text(size = 12),
        axis.title = element_blank(),
        legend.title=element_text(size=12),
        legend.text=element_text(size=12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  scale_color_manual(name="Soil depth", breaks = c("surface", "shallow", "subsurface", "deep"), labels = c("5 cm", "30 cm", "70 cm", "100 cm"), values=c("#009E73", "#999999", "#E69F00", "#56B4E9"))

f <- arrangeGrob(f) #generates f
ggsave(file="fe_weighted_2018.pdf", f, width = 3, height = 3, units = "in")




# C & total Fe & Fe(II) over time (weighted averages)
f <- ggplot(subset(tocmp_melt2018_weighted, element %in% "Fe" & variable %in% c("conc_corrected_mmol_g", "mmol_c_g", "fraction_fe2_per_fe_total"))) +
  aes(x=date, y=weighted.value, color=depth_category2) +
  geom_point() + geom_line() +
  facet_wrap(~location+variable, scales = "free", labeller = labeller(variable = extraction.labs)) +
  labs(color= "Soil depth") +
  theme_bw() +
  theme(strip.text.x = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 12),
        axis.title = element_blank(),
        legend.title=element_text(size=12),
        legend.text=element_text(size=12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

f <- arrangeGrob(f) #generates f
ggsave(file="c_fe_fe2_weighted_2018.pdf", f, width = 10, height = 6, units = "in")

# C & total Fe & Fe(II) over time
f <- ggplot(subset(tocmp_melt2018, element %in% "Fe" & variable %in% c("conc_corrected_mmol_g", "mmol_c_g", "fraction_fe2_per_fe_total"))) +
  aes(x=date, y=value, color=depth_category2) +
  geom_point() + #geom_line() +
  labs(color= "Soil depth") +
  theme_bw() +
  facet_wrap(~location+variable, scales = "free", labeller = labeller(variable = extraction.labs)) +
  theme(strip.text.x = element_text(size = 12, face = "bold"),
        axis.text = element_text(size = 12),
        axis.title = element_blank(),
        legend.title=element_text(size=12),
        legend.text=element_text(size=12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

f <- arrangeGrob(f) #generates f
ggsave(file="c_fe_fe2_2018.pdf", f, width = 10, height = 6, units = "in")

# C-Fe correlations
g <- ggplot(subset(toc_mp_2018, element %in% "Fe")) +
  aes(x=conc_corrected_mmol_g, y=mmol_c_g, color=depth_category2) +
  geom_point() + geom_smooth(method="lm") +
  labs(color= "Soil depth") +
  facet_wrap(~location+season_id, scales = "free") +
  xlab(expression(Iron~(mmol~g^-1))) + ylab(expression(Organic~Carbon~(mmol~g^-1))) +
  theme_bw() +
  scale_x_continuous(breaks = scales::pretty_breaks(3)) +
  scale_y_continuous(breaks = scales::pretty_breaks(4)) +
  theme(strip.text.x = element_blank(),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12),
        legend.position = "none",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_color_manual(name="Soil depth", breaks = c("surface", "shallow", "subsurface", "deep"), labels = c("5 cm", "30 cm", "70 cm", "100 cm"), values=c("#009E73", "#999999", "#E69F00", "#56B4E9"))

g <- arrangeGrob(g) #generates g
ggsave(file="c_fe_correlations_2018.pdf", g, width = 5, height = 4, units = "in")
```

## Stats on 2018 sequential extractions
```{r}
# R2 and p-values for TOC vs. Fe correlations (by extraction)
fe_toc_ham <- subset(toc_mp_2018, element %in% "Fe" & extraction %in% "ham")

fe_toc_ham_surf <- subset(fe_toc_ham, depth_category2 %in% c("surface", "shallow"))
fe_toc_ham_deep <- subset(fe_toc_ham, depth_category2 %in% c("subsurface", "deep"))

fe_toc_ham_surf_early1 <- subset(fe_toc_ham_surf, season_id %in% "early" & location %in% "MCT2-1")
fe_toc_ham_surf_late1 <- subset(fe_toc_ham_surf, season_id %in% "late" & location %in% "MCT2-1")

fe_toc_ham_surf_early3 <- subset(fe_toc_ham_surf, season_id %in% "early" & location %in% "MCT2-3")
fe_toc_ham_surf_late3 <- subset(fe_toc_ham_surf, season_id %in% "late" & location %in% "MCT2-3")


fe_toc_ham_deep_early <- subset(fe_toc_ham_deep, season_id %in% "early")
fe_toc_ham_deep_late <- subset(fe_toc_ham_deep, season_id %in% "late")


# fe_toc_ham_surf_early1
plot(fe_toc_ham_surf_early1$conc_corrected_mmol_g, fe_toc_ham_surf_early1$mmol_c_g)
fe_toc_ham_surf_early1_model <- lm(mmol_c_g ~ conc_corrected_mmol_g, data=fe_toc_ham_surf_early1)
abline(fe_toc_ham_surf_early1_model, col = "red")
summary(fe_toc_ham_surf_early1_model)

# fe_toc_ham_surf_late1
plot(fe_toc_ham_surf_late1$conc_corrected_mmol_g, fe_toc_ham_surf_late1$mmol_c_g)
fe_toc_ham_surf_late1_model <- lm(mmol_c_g ~ conc_corrected_mmol_g, data=fe_toc_ham_surf_late1)
abline(fe_toc_ham_surf_late1_model, col = "red")
summary(fe_toc_ham_surf_late1_model)

# fe_toc_ham_surf_early3
plot(fe_toc_ham_surf_early3$conc_corrected_mmol_g, fe_toc_ham_surf_early3$mmol_c_g)
fe_toc_ham_surf_early3_model <- lm(mmol_c_g ~ conc_corrected_mmol_g, data=fe_toc_ham_surf_early3)
abline(fe_toc_ham_surf_early3_model, col = "red")
summary(fe_toc_ham_surf_early3_model)

# fe_toc_ham_surf_late3
plot(fe_toc_ham_surf_late3$conc_corrected_mmol_g, fe_toc_ham_surf_late3$mmol_c_g)
fe_toc_ham_surf_late3_model <- lm(mmol_c_g ~ conc_corrected_mmol_g, data=fe_toc_ham_surf_late3)
abline(fe_toc_ham_surf_late3_model, col = "red")
summary(fe_toc_ham_surf_late3_model)






# fe_toc_ham_deep_early
plot(fe_toc_ham_deep_early$conc_corrected_mmol_g, fe_toc_ham_deep_early$mmol_c_g)
fe_toc_ham_deep_early_model <- lm(mmol_c_g ~ conc_corrected_mmol_g, data=fe_toc_ham_deep_early)
abline(fe_toc_ham_deep_early_model, col = "red")
summary(fe_toc_ham_deep_early_model)

# fe_toc_ham_deep_late
plot(fe_toc_ham_deep_late$conc_corrected_mmol_g, fe_toc_ham_deep_late$mmol_c_g)
fe_toc_ham_deep_late_model <- lm(mmol_c_g ~ conc_corrected_mmol_g, data=fe_toc_ham_deep_late)
abline(fe_toc_ham_deep_late_model, col = "red")
summary(fe_toc_ham_deep_late_model)


```
