---
title: "East River Soil Processing"
author: "CGA"
date: "June 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
setwd("~/east-river/") #set the working directory
```

## 1. Read in raw soils data
```{r}
soil <- read_excel("Data/June2017_EastRiver_datasheet.xlsx", skip=1) #input your datafile
soil <- soil[-c(1:39),] #removing the hillslope soils

# Make key for sample ID and sample location/depth
soil.key <- soil[,c(1:3)]
soil.key <- soil.key[!duplicated(soil.key), ]

# Print key
#write.csv(soil.key, "22June2017_EastRiver_samplekey.csv")

# Subset just the anaerobic and regular aerobic air dry data
soil.airdry <- soil[,c(1:8, 13)]
soil.airdry <- soil.airdry[!duplicated(soil.airdry$ID), ]

# Subset just the oven dry data for gravimetric water content
soil.ovendry <- soil[,c(1:3, 9:12)]
```

## 2. Process oven dry data for gravimetric water content
```{r}
# Split the sample name into location (MC1-3) and rep (b1-3)
soil.ovendry <- soil.ovendry %>%
  separate(sample, c("location", "rep"), sep="-")

# Split the depth into top/bottom
soil.ovendry <- soil.ovendry %>%
  separate(depth_cm, c("top", "bottom"), sep="-")

# Make "top" and "bottom" columns numeric
soil.ovendry[,c("top","bottom")] <- apply(soil.ovendry[,c("top","bottom")], 2,
                                          function(x) as.numeric(as.character(x)))

# Take the mean of top/bottom depths (change to weighted mean?)
soil.ovendry$mean.depth_cm <- rowMeans(subset(soil.ovendry, select = c(top, bottom)), na.rm = TRUE)

# Column for gravimetric water content (confirm)
soil.ovendry$gwc <- 
  (soil.ovendry$moist_soil_g_oven - (soil.ovendry$dry_tin_g - soil.ovendry$tin_g)) /
  (soil.ovendry$dry_tin_g - soil.ovendry$tin_g)

ggplot(soil.ovendry, aes(x=gwc, y=mean.depth_cm)) +
  geom_point() +
  geom_smooth() +
  scale_y_reverse() +
  facet_wrap(~location)
```

## 3. Process for sieved soil (<2mm), rocks (>2mm), and roots
```{r}
# Read in the processed data
soil.sieved <- read_excel("Data/June2017_EastRiver_RootsRocks.xlsx")
soil.sieved$soil_BAG <- as.factor(soil.sieved$soil_BAG)
soil.sieved$rocks_BAG <- as.factor(soil.sieved$rocks_BAG)

# Convert root biomass from g to mg
soil.sieved$roots_mg <- soil.sieved$roots_g * 1000

# Bag averages to subtract
z <- mean(c("")) #ziploc gallon bag #use same weight as up&up bags
u <- mean(c(11.22, 11.28, 11.28, 11.25)) #up & up gallon bag
q <- mean(c(4.84, 4.81, 4.84, 4.83)) #ziploc quart bag

# Recode the bag variables to their actual weights
soil.sieved$soil_BAG <- as.numeric(as.character(recode_factor(soil.sieved$soil_BAG, `z` = "11.2575", `u` = "11.2575", `q` = "4.83")))
soil.sieved$rocks_BAG <- as.numeric(as.character(recode_factor(soil.sieved$rocks_BAG, `z` = "11.2575", `u` = "11.2575", `q` = "4.83", `na` = "0", `none` = "0")))

# Subtract the bag weights
soil.sieved$soil2mm_g_final <- soil.sieved$soil2mm_g - soil.sieved$soil_BAG
soil.sieved$rocks_g_final <- soil.sieved$rocks_g - soil.sieved$rocks_BAG

# Soil/rock fractions
soil.sieved$soil_frac <- soil.sieved$soil2mm_g_final / 
  (soil.sieved$soil2mm_g_final + soil.sieved$rocks_g_final + soil.sieved$roots_g)
soil.sieved$rock_frac <- soil.sieved$rocks_g / 
  (soil.sieved$soil2mm_g + soil.sieved$rocks_g + soil.sieved$roots_g)
  
# Root biomass (mg roots/g soil)
soil.sieved$root_frac <- soil.sieved$roots_mg / 
  (soil.sieved$soil2mm_g_final)

# Split the sample name into location (MC1-3) and rep (b1-3)
soil.sieved <- soil.sieved %>%
  separate(sample, c("location", "rep"), sep="-")

# Split the depth into top/bottom
soil.sieved <- soil.sieved %>%
  separate(depth_cm, c("top", "bottom"), sep="-")

# Make "top" and "bottom" columns numeric
soil.sieved[,c("top","bottom")] <- apply(soil.sieved[,c("top","bottom")], 2,
                                          function(x) as.numeric(as.character(x)))
# Take the mean of top/bottom depths (change to weighted mean?)
soil.sieved$mean.depth_cm <- rowMeans(subset(soil.sieved, select = c(top, bottom)), na.rm = TRUE)

# Write processed datasheet
soil.sieved.print <- soil.sieved[,c("ID","location","rep","top","bottom","mean.depth_cm","soil2mm_g_final","rocks_g_final","roots_mg","soil_frac","rock_frac","root_frac")]

soil.sieved.print <- soil.sieved.print[with(soil.sieved.print, order(location,rep,top)),]

#write.csv(soil.sieved.print, "June2017_EastRiver_soil_processed.csv")
```

## 4. Figures of 2mm fraction, root biomass
```{r}
# Root figures
# Root biomass (not standardized)
ggplot(soil.sieved, aes(x=(roots_mg), y=mean.depth_cm, color=location)) +
  geom_point() +
#  geom_smooth() +
  scale_y_reverse() +
  xlab("Root biomass (mg)") +
  ylab("Depth (cm)")

ggplot(soil.sieved, aes(x=log(roots_mg), y=mean.depth_cm, color=location)) +
  geom_point() +
  geom_smooth(method="lm") +
  scale_y_reverse() +
  xlab("Log(Root biomass (mg))") +
  ylab("Depth (cm)")

# Root biomass (mg roots g-1 soil)
ggplot(soil.sieved, aes(x=root_frac, y=mean.depth_cm, color=location)) +
  geom_point() +
#  geom_smooth(method="lm") +
  scale_y_reverse() +
  xlab("Root biomass per g sieved soil (mg root/g soil)") +
  ylab("Depth (cm)")

ggplot(soil.sieved, aes(x=log(root_frac), y=mean.depth_cm, color=location)) +
  geom_point() +
#  geom_smooth(method="lm") +
  scale_y_reverse() +
  xlab("Log root biomass per g sieved soil (log(mg root/g soil))") +
  ylab("Depth (cm)")

# Fraction <2mm (by air dry weight)
ggplot(soil.sieved, aes(x=soil_frac, y=mean.depth_cm, color=location)) +
  geom_point() +
#  geom_smooth() +
  scale_y_reverse() +
  xlab("Fraction <2mm (by air dry weight)") +
  ylab("Depth (cm)")
```
