---
title: "EastRiver_flux_redox"
author: "CGA"
date: "June 17, 2018"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary packages
library(tidyverse)
library(readxl)
library(gridExtra)
library(grid)
# Set working directory
setwd("~/east-river/")
```

## Load data
```{r}
### Reading in all data
#https://stackoverflow.com/questions/47511319/read-all-worksheets-as-dataframes-from-multiple-excel-workbooks-of-different-s

read_excel_allsheets <- function(filename) {
    sheets <- readxl::excel_sheets(filename)
    x <-    lapply(sheets, function(X) readxl::read_excel(filename, sheet = X))
    names(x) <- sheets
    x
}

mysheets <- read_excel_allsheets('Data/2018_fielddata/11Dec2018_MCT2 Instrumentation and Sampling.xlsx')
mysheets2 <- read_excel_allsheets('Data/2019_fielddata/2019-10-22_field_monitoring_2019.xlsx')

# 2018 data
rhizon_key <- as.data.frame(mysheets[1])
rhizon_vials <- as.data.frame(mysheets[2])
solid_key <- as.data.frame(mysheets[3])
well_data <- as.data.frame(mysheets[4])
licor_key <- as.data.frame(mysheets[5])
flux <- as.data.frame(mysheets[6])
redox_key <- as.data.frame(mysheets[7])
redox <- as.data.frame(mysheets[8])

# Column names 2018
names(rhizon_key) <- gsub(pattern = "Rhizon.Probe.Key.", replacement = "", x = names(rhizon_key))
names(rhizon_vials) <- gsub(pattern = "Rhizon_vials.", replacement= "", x=names(rhizon_vials))
names(solid_key) <- gsub(pattern = "Solid.Sampling.Key.", replacement = "", x = names(solid_key))
names(well_data) <- gsub(pattern = "Well.Sampling.Data.", replacement = "", x = names(well_data))
names(licor_key) <- gsub(pattern = "LI.COR.Key.", replacement = "", x = names(licor_key))
names(flux) <- gsub(pattern = "LI.COR.Data.", replacement = "", x = names(flux))
names(redox_key) <- gsub(pattern = "Redox.Key.", replacement = "", x = names(redox_key))
names(redox) <- gsub(pattern = "Redox.Data.", replacement = "", x = names(redox))

# 2019 data
flux2019 <- as.data.frame(mysheets2[3])
redox2019 <- as.data.frame(mysheets2[1])
well_data2019 <- as.data.frame(mysheets2[4])
solid_key2019 <- as.data.frame(mysheets2[2])

# Column names 2019
names(flux2019) <- gsub(pattern = "licor_data.", replacement = "", x = names(flux2019))
names(redox2019) <- gsub(pattern = "redox_data.", replacement= "", x=names(redox2019))
names(well_data2019) <- gsub(pattern = "well_data.", replacement = "", x = names(well_data2019))
names(solid_key2019) <- gsub(pattern = "soil_sampling.", replacement = "", x = names(solid_key2019))
```

## Tidy flux data
```{r}
# Change flux 2018 column names to match 2019
colnames(flux) <- c("date", "time", "location_mct2", "collar_number", "temp_C", "moisture", "rep1", "rep2", "rep3", "notes")

# add "MCT2-" to flux2019 location column
flux2019$location_mct2 <- sub("^", "MCT2-", flux2019$location_mct2)

# Change column structures
flux[, c("moisture", "rep1", "rep2", "rep3")] <-
  as.numeric(as.character(unlist(flux[c("moisture", "rep1", "rep2", "rep3")])))
flux$location_mct2 <- as.factor(flux$location_mct2)
  
flux2019[,c("time", "temp_C","v1", "v2", "v3", "v4", "rep1", "rep2", "rep3")] <- 
  as.numeric(as.character(unlist(flux2019[,c("time", "temp_C","v1", "v2", "v3", "v4", "rep1", "rep2", "rep3")])))

# Make datetime column
flux$date <- format(flux$date, format = "%m/%d/%Y")
flux$time <- format(flux$time, format = "%H:%M")
flux$datetime <- -999
flux$datetime <- as.POSIXct(paste(flux$date, flux$time), format="%m/%d/%Y %H:%M")

flux2019$date <- format(flux2019$date, format = "%m/%d/%Y")
#force flux2019$time = 12:00:00
flux2019$time <- "12:00:00"
flux2019$time <- chron::times(flux2019$time)
flux2019$datetime <- as.POSIXct(paste(flux2019$date, flux2019$time), format="%m/%d/%Y %H:%M")

# Flux average (To do: exclude outliers based on SD)
flux$flux.av <- rowMeans(flux[, c(7,8,9)], na.rm = TRUE)
flux2019$flux.av <- rowMeans(flux2019[, c(10, 11, 12)], na.rm = TRUE)

# Merge flux with licor key
colnames(licor_key) <- c("location_mct2", "collar_number", "environment", "observed_moisture", "offset_height_cm")
flux_total <- merge(flux, licor_key)
flux_total2019 <- merge(flux2019, licor_key)
```

## Tidy redox data
```{r}
redox$Probe[redox$Probe == "8b"] <- 8

# Changing column names
colnames(redox) <- c("date", "time", "location_mct2", "probe", "mv1", "mv2")
# Extracting time from redox 2018
redox$time <- strftime(redox$time, format = "%H:%M", tz="UTC")
# Adding arbitrary sampling times to Christian's redox sampling
redox$time[redox$date %in% c("09/22/2018", "09/11/2018", "08/26/2018")] <- "12:00"
           
# Make datetime column
redox$date <- format(redox$date, format = "%m/%d/%Y")
redox$date[redox$date == "05/29/2018"] <- ("05/30/2018") #Change 5/29 to 5/30 to match with licor
redox$datetime <- -999
redox$datetime <- as.POSIXct(paste(redox$date, redox$time), format="%m/%d/%Y %H:%M")

redox2019$date <- format(redox2019$date, format = "%m/%d/%Y")
redox2019$time <- "12:00"
redox2019$datetime <- -999
redox2019$datetime <- as.POSIXct(paste(redox2019$date, redox2019$time), format="%m/%d/%Y %H:%M")

# add "MCT2-" to redox2019 location column
redox2019$location_mct2 <- sub("^", "MCT2-", redox2019$location_mct2)

# Merge with redox key
colnames(redox_key) <- c("location_mct2", "probe", "color", "depth_cm")
redox_total <- merge(redox, redox_key)
redox_total2019 <- merge(redox2019, redox_key)

# Redox average
redox_total$mv1 <- as.numeric(redox_total$mv1)
redox_total$mv2 <- as.numeric(redox_total$mv2)
redox_total$redox_av <- rowMeans(redox_total[, c(5,6)], na.rm = TRUE)

# Corrected redox values (add 254)
redox_total$redox_av.corrected <- redox_total$redox_av + 254
redox_total2019$redox_av.corrected <- redox_total2019$mv_uncorrected + 254

# Aggregate depths (average of duplicate/triplicates)
redox_av.means <- aggregate(redox_av.corrected~location_mct2+datetime+date+depth_cm, redox_total, mean)
redox_av.means2019 <- aggregate(redox_av.corrected~location_mct2+datetime+date+depth_cm, redox_total2019, mean)

```

## Combine flux and redox data
```{r}
# Merge CO2 flux and redox
#redox_av.means$datetime <- NULL #might need to add this back in, but it messes up redox_av.means if included.
redox_av.means$depth_cm <- as.factor(redox_av.means$depth_cm)
redox_av.means2019$depth_cm <- as.factor(redox_av.means2019$depth_cm)

flux_redox <- merge(flux_total, redox_av.means, by=c("date", "location_mct2"))
flux_redox2019 <- merge(flux_total2019, redox_av.means2019, by=c("date", "location_mct2"))
```

## Merge with water table depth data
```{r}
# First, run EastRiver_watertabledepth.Rmd to get processed water table depth data

# Merge flux_total or flux_redox with wtd_interp
flux_total$date <- as.Date(flux_total$datetime)
flux_redox$date <- as.Date(flux_redox$datetime)

flux_watertable <- merge(flux_redox, wtd_interp) # was some data lost in the merge?

flux_watertable$date <- xtfrm(flux_watertable$date)
```

## Figures
```{r}
## Flux figures
g <- ggplot(subset(flux_total)) +
  aes(x=datetime, y=flux.av, color = moisture) + # adding color = moisture for dissertation proposal figure
  geom_point() +
  geom_smooth() +
  ylab("Soil respiration (CO2 flux)") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 25),
        strip.text.x = element_text(size = 25),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20)) +
  facet_wrap(~location_mct2)

flux_total2019$date <- as.Date(flux_total2019$date, format = "%m/%d/%y")
flux_total$date <- as.Date(flux_total$date, format = "%m/%d/%y")


ggplot(subset(flux_total2019, rep3 > 0 & rep3 < 10)) +
  aes(x=date, y=rep3) + # adding color = moisture for dissertation proposal figure
  geom_point() +
  geom_smooth() +
  ylab("Soil respiration (CO2 flux)") +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        strip.text.x = element_text(size = 20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20)) +
  facet_wrap(~location_mct2)

ggplot(subset(flux_total, rep3 > 0 & rep3 < 10)) +
  aes(x=date, y=rep3) + # adding color = moisture for dissertation proposal figure
  geom_point() +
  geom_smooth() +
  ylab("Soil respiration (CO2 flux)") +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        strip.text.x = element_text(size = 20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20)) +
  facet_wrap(~location_mct2)

#ggsave(file="flux-2018-moisture.pdf", g, width = 10, height = 4, units = "in")

ggplot(subset(flux_total)) + #flux_total2019
  aes(x=temp_C, y=flux.av) +
  geom_point() +
  geom_smooth() +
  xlab("Soil temperature (C)") + ylab("Soil respiration (CO2 flux)") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 25),
        strip.text.x = element_text(size = 25),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  facet_wrap(~location_mct2)

ggplot(subset(flux_total)) +
  aes(x=moisture, y=flux.av, color=as.POSIXct(date, format= "%m/%d/%Y")) + #, color=Environment
  geom_point() +
  geom_smooth() +
  xlab("Soil moisture (volumetric)") + ylab("Soil respiration (CO2 flux)") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 25),
        strip.text.x = element_text(size = 25),
        legend.title=element_text(size=20),
        legend.text=element_text(size=20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  guides(color=guide_legend(title="Date")) +
  facet_wrap(~location_mct2)

ggplot(subset(flux_total)) +
  aes(x=as.POSIXct(time, format= "%H:%M"), y=flux.av, color=as.POSIXct(time, format= "%H:%M")) +
  geom_point() +
  geom_smooth() +
  xlab("Date") + ylab("Soil respiration (CO2 flux)") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  facet_wrap(~location_mct2)

## Redox figures
ggplot(redox_total2019) +
  aes(x=datetime, y=redox_av.corrected, color=as.factor(depth_cm)) +
  geom_point() +
  geom_smooth() +
  xlab("Date") + ylab("Eh (mV)") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 25),
        strip.text.x = element_text(size = 25),
        legend.title=element_text(size=20),
        legend.text=element_text(size=20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  facet_wrap(~location_mct2) +
  guides(color=guide_legend(title="Soil depth (cm)"))

ggplot(subset(redox_av.means2019)) +
  aes(x=datetime, y=redox_av.corrected, color=as.factor(depth_cm)) +
  #scale_x_datetime(date_breaks = "1 month", date_labels = "%B") +
  geom_point() +  geom_smooth() +
  xlab("Date") + ylab("Redox potential (mV)") +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank()) +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~location_mct2)

## Flux and redox figures
ggplot(flux_redox) +
  aes(x=redox_av.corrected, y=moisture) +
  geom_point() +
  facet_wrap(~depth_cm)

ggplot(flux_redox) +
  aes(x=redox_av.corrected, y=flux.av) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~depth_cm, scales="free")

ggplot(flux_redox) +
  aes(x=redox_av.corrected, y=flux.av, color=moisture) +
  geom_point() +
#  geom_smooth() +
  facet_wrap(~depth_cm, scales="free")

ggplot(subset(flux_redox, redox_av.corrected < 0)) +
  aes(x=redox_av.corrected, y=flux.av, color=moisture) +
  geom_point() +
#  geom_smooth() +
  facet_wrap(~depth_cm + location_mct2, scales="free")

ggplot(subset(flux_redox, depth_cm == 100)) +
  aes(x=redox_av.corrected, y=flux.av, color=moisture) +
  geom_point() +
#  geom_smooth() +
  facet_wrap(~depth_cm + location_mct2, scales="free")

## Flux, redox, water table depth figures
ggplot(flux_watertable) +
  aes(x= flux.av, y=wtd_cm) +
  geom_point() +
  facet_wrap(~Location, scales="free")

ggplot(subset(flux_watertable, depth_cm %in% 15)) +
  aes(x=datetime, y=wtd_cm) + #, color=Environment
  scale_y_reverse() +
  geom_point() +
  geom_smooth() +
  xlab("Date") + ylab("Water table depth (cm)") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 25),
        strip.text.x = element_text(size = 25),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  facet_wrap(~Location)

ggplot(subset(flux_watertable, depth_cm %in% 15)) +
  aes(x=wtd_cm, y=Moisture) +
  geom_point() +
  geom_smooth() +
  xlab("Water table depth (cm)") + ylab("Soil moisture (volumetric)") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  facet_wrap(~Location, scales="free")

ggplot(flux_watertable) +
  aes(x=wtd_cm, y=redox_av.corrected, color=depth_cm) +
  geom_point() +
  geom_smooth() +
  coord_flip() +
  scale_x_reverse() +
  xlab("Water table depth (cm)") + ylab("Eh (mV)") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 25),
        strip.text.x = element_text(size = 25),
        legend.title=element_text(size=20),
        legend.text=element_text(size=20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~Location)
```

## Temperature sensitivity (Q10)
```{r}
## Davidson 2012, DAMM

## Abramoff
# Arrhenius Model (The Arrhenius equation to estimate the rate of a reaction is a null model to the more process-based models DAMM and DAMM-MCNiP);  This model is based on the assumption that temperature is the main effect on the depolymerization rate, and that depolymerization is the rate-limiting process controlling C efflux.
# FC = α * e-Ea/RT
# α is the pre-exponential constant (mg C cm-3 hr-1), T is soil temperature (K) at 10 cm depth, Ea is the activation energy (kJ/mol), and R is the universal gas constant (kJ mol-1 K-1).
# alpha = 5.38 x 10^10 (Davidson)
# Ea = 72.26 (Davidson)
# R = 0.00831447 kJ mol-1 K-1
# T = soil temp
flux_total$FC <- -999
flux_total$FC <- (5.38 * 10^10) * exp(72.26/(0.00831447*flux$temp_C))

ggplot(flux_total) +
  aes(x=FC, y=flux.av) +
  geom_point()

# Dual Arrhenius and Michaelis-Menten Model: DAMM simulates the effects of soil temperature, soil moisture and substrate supply on soil organic matter (SOM) depolymerization. Depolymerization is affected by soil temperature according to Arrhenius kinetics. Soil water content modifies the supply of two substrates, oxygen and a generalized C-containing substrate, both of which affect depolymerization using a Michaelis-Menten (i.e., dual Monod) kinetic approximation)
# Calculation for Depolymerization rate, using Vmax from Arrhenius equation
```

## Stockbridge lightning talk: Combine with river height data for figure, redox
```{r}
# First run EastRiver_almont.Rmd script to get river height data (dataframe = "discharge")
# p1 = flux vs. time from 5/30 thru 9/22
# p2 = river height vs. time from 5/30 thru 9/22

p1 <- ggplot(subset(flux_total, location_mct2 == "MCT2-1")) +
  aes(x=datetime, y=flux.av) +
  geom_point() +
  geom_smooth() +
  #xlab("Date") + ylab("Soil respiration (CO2 flux)") +
  theme_bw() +
  theme(axis.text.y = element_text(size = 33),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 33),
        strip.text.x = element_text(size = 25),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank())


lims <- as.POSIXct(strptime(c("2018-05-29 00:00:00", "2018-09-23 00:00:00"), format = "%Y-%m-%d %H:%M"))

p2 <- ggplot(discharge) +
  aes(x=datetime, y=gageheight_m) +
  scale_x_datetime(limits = lims) + 
  geom_line(color="blue", size=1) +
  xlab("Date") + ylab("East River height (m)") +
  theme_bw() +
  theme(axis.text = element_text(size = 33),
        axis.title = element_text(size = 33),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank())

# Stack the plots
g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g <- rbind(g1, g2, size="first")
g$widths <- unit.pmax(g1$widths, g2$widths)
grid.newpage()
grid.draw(g)

# Redox
ggplot(subset(redox_av.means, location_mct2 == "MCT2-1" & depth_cm %in% c(15, 70, 100))) +
  aes(x=datetime, y=redox_av.corrected, color=as.factor(depth_cm)) +
  scale_x_datetime(date_breaks = "1 month", date_labels = "%B") +
  geom_point() +
  geom_smooth() +
  xlab("Date") + ylab("Redox potential (mV)") +
  theme_bw() +
  theme(axis.text = element_text(size = 33),
        axis.title = element_text(size = 33),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank()) +
  guides(color=guide_legend(title="Soil depth (cm)"))
```

## DOE PI meeting poster for May 2019, and GCC poster for November 2019
```{r}
# Need stacked plots of these variables over time:
# CO2 flux
# TOC (also for wells)
# Fe, SO4, Mn, etc. (also for wells)
# moisture from Acclima
# Redox, and/or water table depth

# Make sure dates line up; put date on bottom graph; make legends match (same titles, color, etc.)
lims <- as.POSIXct(strptime(c("2018-06-02 00:00:00", "2018-10-09 00:00:00"), format = "%Y-%m-%d %H:%M"))

lims_2018 <- as.POSIXct(strptime(c("2018-06-02 00:00:00", "2018-10-09 00:00:00"), format = "%Y-%m-%d %H:%M"))

lims_2019 <- as.POSIXct(strptime(c("2019-06-02 00:00:00", "2019-10-09 00:00:00"), format = "%Y-%m-%d %H:%M"))


# Name transect positions 1, 3, 4
position_names <- c(
                    "MCT2-1" = "1",
                    "MCT2-3" = "3",
                    "MCT2-4" = "4"
                    )

# Colorblind palette with grey:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


p1 <- ggplot(subset(wtd_interp, Location %in% c("MCT2-1", "MCT2-3"))) +
  aes(x=as.POSIXct(date), y=wtd_cm) +
  scale_y_reverse() +
  ylab("Water table depth (cm)") +
  geom_point(size=1) + geom_smooth(size=1) +
  facet_wrap(~Location) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 20),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 18),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        strip.text = element_blank()) +
  xlim(lims)

# acclima moisture 2018
p2 <- ggplot(subset(acclima_av, location %in% c("MCT2-1","MCT2-3") & depth_cm %in% c("30", "70"))) +
  aes(x=date, y=moisture_mean, color=depth_cm) +
  geom_point(size = 1) +
  xlab("Time") + ylab("moisture (%)") +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~location, labeller = as_labeller(position_names)) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 20),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank()) +
  xlim(lims_2018) +
  scale_color_manual(values=cbPalette)

# acclima moisture 2019
p2b <- ggplot(subset(acclima_av, location %in% c("MCT2-1","MCT2-3") & depth_cm %in% c("30", "70"))) +
  aes(x=date, y=moisture_mean, color=depth_cm) +
  geom_point(size = 1) +
  xlab("Time") + ylab("moisture (%)") +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~location, labeller = as_labeller(position_names)) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 20),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank()) +
  xlim(lims_2019) +
  scale_color_manual(values=cbPalette)

# redox 2018
p3 <- ggplot(subset(redox_av.means, location_mct2 %in% c("MCT2-1","MCT2-3") & depth_cm %in% c("30", "70", "100"))) +
  aes(x=datetime, y=redox_av.corrected, color=as.factor(depth_cm)) +
  geom_point(size=2) + geom_smooth(size=1) +
  ylab("Eh (mV)") +
  ylim(-250, 500) +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~location_mct2, labeller = as_labeller(position_names)) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlim(lims_2018) +
  scale_color_manual(values=cbPalette)

p3.2 <- ggplot(subset(redox_av.means, location_mct2 %in% c("MCT2-3") & depth_cm %in% c("30", "70", "100"))) +
  aes(x=datetime, y=redox_av.corrected, color=as.factor(depth_cm)) +
  geom_point(size=2) + geom_smooth(size=1) +
  ylab("Eh (mV)") +
  ylim(-250, 500) +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~location_mct2, labeller = as_labeller(position_names)) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlim(lims_2018) +
  scale_color_manual(values=cbPalette)

# redox 2019
p3b <- ggplot(subset(redox_av.means2019, location_mct2 %in% c("MCT2-1","MCT2-3") & depth_cm %in% c("30", "70", "100"))) +
  aes(x=datetime, y=redox_av.corrected, color=as.factor(depth_cm)) +
  geom_point(size=2) + geom_smooth(size=1) +
  ylab("Eh (mV)") +
  ylim(-250, 500) +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~location_mct2, labeller = as_labeller(position_names)) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlim(lims_2019) +
  scale_color_manual(values=cbPalette)

p3b.2 <- ggplot(subset(redox_av.means2019, location_mct2 %in% c("MCT2-3") & depth_cm %in% c("30", "70", "100"))) +
  aes(x=datetime, y=redox_av.corrected, color=as.factor(depth_cm)) +
  geom_point(size=2) + geom_smooth(size=1) +
  ylab("Eh (mV)") +
  ylim(-250, 500) +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~location_mct2, labeller = as_labeller(position_names)) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlim(lims_2019) +
  scale_color_manual(values=cbPalette)


# flux 2018
p4 <- ggplot(subset(flux_total, flux.av > 0 & flux.av < 5 & location_mct2 %in% c("MCT2-1","MCT2-3"))) +
  aes(x=datetime, y=flux.av) +
  geom_point(size=2) +  geom_smooth(size=2) +
  ylab("Surface CO2 flux") +
  ylim(0.1,4) +
  facet_wrap(~location_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        strip.text = element_blank()) +
  xlim(lims_2018)

p4.2 <- ggplot(subset(flux_total, flux.av > 0 & flux.av < 5 & location_mct2 %in% c("MCT2-3"))) +
  aes(x=datetime, y=flux.av) +
  geom_point(size=2) +  geom_smooth(size=2) +
  ylab("Surface CO2 flux") +
  ylim(0.1,4) +
  facet_wrap(~location_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        strip.text = element_blank()) +
  xlim(lims_2018)

# flux 2019
p4b <- ggplot(subset(flux_total2019, flux.av > 0 & flux.av < 7 & location_mct2 %in% c("MCT2-1","MCT2-3"))) +
  aes(x=datetime, y=flux.av) +
  geom_point(size=2) +  geom_smooth(size=2) +
  ylab("Surface CO2 flux") +
  ylim(0.1,4) +
  facet_wrap(~location_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        strip.text = element_blank()) +
  xlim(lims_2019)

p4b.2 <- ggplot(subset(flux_total2019, flux.av > 0 & flux.av < 7 & location_mct2 %in% c("MCT2-3"))) +
  aes(x=datetime, y=flux.av) +
  geom_point(size=2) +  geom_smooth(size=2) +
  ylab("Surface CO2 flux") +
  ylim(0.1,4) +
  facet_wrap(~location_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        strip.text = element_blank()) +
  xlim(lims_2019)


# NPOC 2018
p5 <- ggplot(subset(rhiz_toc_av, TOC_mm_mean < 9 & position_mct2 %in% c(1,3) & depth_class %in% c("30-40", "60-80", "80-100"))) +
  aes(x=as.POSIXct(date), y=TOC_mm_mean, color=depth_class) +
  geom_point(size=2) + geom_line(size=1) +
  ylab("NPOC (mM)") +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~position_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlim(lims_2018) +
  scale_color_manual(values=cbPalette)

# NPOC 2019 (empty for now)
p5b <- ggplot(subset(rhiz_toc_av, TOC_mm_mean < 9 & position_mct2 %in% c(1,3) & depth_class %in% c("30-40", "60-80", "80-100"))) +
  aes(x=as.POSIXct(date), y=TOC_mm_mean, color=depth_class) +
  geom_point(size=2) + geom_line(size=1) +
  ylab("NPOC (mM)") +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~position_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  xlim(lims_2019) +
  scale_color_manual(values=cbPalette)




p6 <- ggplot(subset(rhiz_icp_av, position_mct2 %in% c(1,3) & depth_class %in% c("30-40", "60-80", "80-100"))) +
  aes(x=as.POSIXct(date), y=SO4_mean, color=depth_class) +
  geom_point(size=3) + geom_line(size=2) +
  ylab("SO4 (mM)") +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~position_mct2) +
  theme_bw() +
  theme(axis.text = element_text(size = 20),
        #axis.text.x = element_blank(),
        axis.title = element_text(size = 20),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank()) +
  xlim(lims) +
  scale_color_manual(values=cbPalette)



p7 <- ggplot(subset(rhiz_icp_av, position_mct2 %in% c(1,3) & depth_class %in% c("30-40", "60-80", "80-100"))) +
  aes(x=as.POSIXct(date), y=NO3_mean, color=depth_class) +
  geom_point() + geom_line() +
  ylab("NO3 (mM)") +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~position_mct2) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 12),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank()) +
  xlim(lims) +
  scale_color_manual(values=cbPalette)

p8 <- ggplot(subset(rhiz_icp_av, position_mct2 %in% c(1,3) & depth_class %in% c("30-40", "60-80", "80-100"))) + #& Fe_mean < 4.677414e-06
  aes(x=as.POSIXct(date), y=Fe_mean*1000, color=depth_class) +
  geom_point() + geom_line() +
  ylab("Fe (mM)") +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~position_mct2) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 12),
        axis.text.x = element_blank(),
        axis.title = element_text(size = 12),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank()) +
  xlim(lims) +
  scale_color_manual(values=cbPalette) +  ylim(0, 0.04)

p9 <- ggplot(subset(rhiz_icp_av, position_mct2 %in% c(1,3) & depth_class %in% c("30-40", "60-80", "80-100"))) +
  aes(x=as.POSIXct(date), y=Mn_mean*1000, color=depth_class) +
  geom_point() + geom_line() +
  ylab("Mn (mM)") +
  guides(color=guide_legend(title="Soil depth (cm)")) +
  facet_wrap(~position_mct2) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 12),
        #axis.text.x = element_blank(),
        axis.title = element_text(size = 12),
        #strip.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x=element_blank(),
        legend.position = "none",
        strip.text = element_blank()) +
  xlim(lims) +
  scale_color_manual(values=cbPalette)



# Stack the 2018 moisture & redox
g2 <- ggplotGrob(p2)
g3 <- ggplotGrob(p3)
g <- rbind(g2, g3, size="first")
g$widths <- unit.pmax(g2$widths, g3$widths)
grid.newpage()
grid.draw(g)
g <- arrangeGrob(g) #generates g
ggsave(file="moisture_redox2018.pdf", g, width = 5, height = 5, units = "in")


# Stack the 2019 moisture & redox
g2b <- ggplotGrob(p2b)
g3b <- ggplotGrob(p3b)
gb <- rbind(g2b, g3b, size="first")
gb$widths <- unit.pmax(g2b$widths, g3b$widths)
grid.newpage()
grid.draw(gb)
gb <- arrangeGrob(gb) #generates g
ggsave(file="moisture_redox2019.pdf", gb, width = 5, height = 5, units = "in")

# Stack the 2018 CO2 flux & DOC
g4 <- ggplotGrob(p4)
g5 <- ggplotGrob(p5)
gflux <- rbind(g4, g5, size="first")
gflux$widths <- unit.pmax(g4$widths, g5$widths)
grid.newpage()
grid.draw(gflux)
gflux <- arrangeGrob(gflux) #generates g
ggsave(file="flux_doc2018.pdf", gflux, width = 5, height = 5, units = "in")

# Stack the 2019 CO2 flux & DOC
g4b <- ggplotGrob(p4b)
g5b <- ggplotGrob(p5b)
gfluxb <- rbind(g4b, g5b, size="first")
gfluxb$widths <- unit.pmax(g4b$widths, g5b$widths)
grid.newpage()
grid.draw(gfluxb)
gfluxb <- arrangeGrob(gfluxb) #generates g
ggsave(file="flux_doc2019.pdf", gfluxb, width = 5, height = 5, units = "in")

# Stack the 2018 redox & flux
g3.2 <- ggplotGrob(p3.2)
g4.2 <- ggplotGrob(p4.2)
gflux <- rbind(g4.2, g3.2, size="first")
gflux$widths <- unit.pmax(g3.2$widths, g4.2$widths)
grid.newpage()
grid.draw(gflux)
gflux <- arrangeGrob(gflux) #generates g
ggsave(file="redox_flux_2018.pdf", gflux, width = 3, height = 5, units = "in")

# Stack the 2019 redox & flux
g3b.2 <- ggplotGrob(p3b.2)
g4b.2 <- ggplotGrob(p4b.2)
gfluxb <- rbind(g4b.2, g3b.2, size="first")
gfluxb$widths <- unit.pmax(g3b.2$widths, g4b.2$widths)
grid.newpage()
grid.draw(gfluxb)
gfluxb <- arrangeGrob(gfluxb) #generates g
ggsave(file="redox_flux_2019.pdf", gfluxb, width = 3, height = 5, units = "in")


# Stack the plots (wtd, moisture, redox, flux, moisture/wtd, NPOC)
g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g3 <- ggplotGrob(p3)
g4 <- ggplotGrob(p4)
g5 <- ggplotGrob(p5)


g <- rbind(g1, g2, g3, g4, g5, size="first")
g$widths <- unit.pmax(g2$widths, g3$widths)
grid.newpage()
grid.draw(g)

#save
g <- arrangeGrob(g) #generates g
ggsave(file="mc-env-final.pdf", g, width = 8, height = 13.75, units = "in") #saves g, h = 11 for 4




# Stack the plots (NPOC, SO4)
g5 <- ggplotGrob(p5)
g6 <- ggplotGrob(p6)

g <- rbind(g5, g6, size="first")
g$widths <- unit.pmax(g5$widths, g6$widths)
grid.newpage()
grid.draw(g)

#save
g <- arrangeGrob(g) #generates g
ggsave(file="mc-rhiz-final.pdf", g, width = 8, height = 5.5, units = "in") #saves g

```