---
title: "East River Coordinates""
author: "CGA"
date: "June 9, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggmap)
library(ggrepel)
library(stringr)
setwd("~/east-river/") #set the working directory
```

## 1. Read in raw GPS data
```{r}
gps <- read.csv("Data/8June2017_EastRiverGPS.csv") #input your datafile
gps.sub <- subset(gps, select = -c(Date.Created, Description, Northing, Easting)) #removing some columns
gps.sub <- gps.sub[-c(6, 8, 10), ] #getting relevant sampling locations
colnames(gps.sub) <- c("name","lat","lon")
```

## 2. Load and generate ggmap
```{r}
# Making a map of the points
mapeastriver <- get_map(location = c(lon = mean(gps.sub$lon), lat = mean(gps.sub$lat)),
                        zoom = 17, maptype = "satellite", scale=2)

p <- ggmap(mapeastriver) + geom_point(data = gps.sub, aes(x=lon, y=lat), color="red")
#p <- p + geom_label_repel(data = gps.sub, aes(lon, lat, label=name), color="black", size=4)
p <- p +  geom_label_repel(
  data = gps.sub, aes(lon, lat, label = name),
  fontface = 'bold', color = 'black',
  box.padding = unit(0.35, "lines"),
  point.padding = unit(0.5, "lines"),
  segment.color = 'white')

print(p)


# Print empty map of site
p1 <- ggmap(mapeastriver)
print(p1)

# Print only sampled transect
gps.sub2 <- gps.sub[c(1,5,6), ]
gps.sub2$name2 <- str_sub(gps.sub2$name, 1, str_length(gps.sub2$name)-3)

mapeastriver2 <- get_map(location = c(lon = mean(gps.sub2$lon), lat = mean(gps.sub2$lat)),
                        zoom = 18, maptype = "satellite", scale=2)

p2 <- ggmap(mapeastriver2) +
  geom_line(data = gps.sub2, aes(x=lon, y=lat), color="yellow", size=1) +
  geom_point(data = gps.sub2, aes(x=lon, y=lat), color="yellow", size=2)
#p2 <- p2 +  geom_label_repel(
#  data = gps.sub2, aes(lon, lat, label = name2),
#  fontface = 'bold', color = 'black',
#  box.padding = unit(0.35, "lines"),
#  point.padding = unit(0.5, "lines"),
#  segment.color = 'white')

print(p2)
```

##. 3. For zoomed figure of field site
```{r}
# Colorado map
colorado <- get_map('colorado', zoom = 6, maptype = "satellite", source = "google")

ggmap(colorado) +
  geom_path(data=map_data("state"), aes(x=long, y=lat), color="white", size=2) +
  coord_map(xlim=c(-110, -101), ylim=c(36, 41.5))

# RMBL map
lat <- c(38.886, 39)                
lon <- c(-107.056967, -106.870604)

get_googlemap(center = c(lon = mean(lon), lat = mean(lat)),
              zoom = 12, maptype = "terrain") %>%
  ggmap() 

# Coordinates for Mt. Crested Butte and RMBL
location <- c("Mt. Crested Butte", "RMBL")
latitude <- c(38.9122, 38.9585)
longitude <- c(-106.9624, -106.9878)

gps.map <- data.frame(location, latitude, longitude)

# RMBL map without terrain labels, with labels for Mt. Crested Butte and RMBL
#https://stackoverflow.com/questions/36367335/ggmap-removing-country-names-from-googles-terrain-map
#https://developers.google.com/maps/documentation/static-maps/styling#features
get_googlemap(center = c(lon = mean(lon), lat = mean(lat)),
              zoom = 12, maptype = "terrain",
              style = c('feature:landscape|element:labels|visibility:off',
                        'feature:administrative|element:labels|visibility:off',
                        'feature:poi|element:labels|visibility:off')) %>%
  ggmap() + 
  geom_point(data = gps.map, aes(x=longitude, y=latitude), color="red", size=4) +
  geom_label_repel(data = gps.map, aes(longitude, latitude, label = location),
                   fontface = 'bold', color = 'black',
                   box.padding = unit(0.5, "lines"),
                   point.padding = unit(0.5, "lines"),
                   segment.color = 'red',
                   segment.size = 2)
```
