---
title: "total_cn"
author: "CGA"
date: "November 25, 2017"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary packages
library(tidyverse)
library(readxl)
library(reshape2)
library(zoo)
# Set working directory
setwd("~/east-river/")
```

## LOI on June 2017 samples (run Aug 2019)
```{r}
loi <- read_excel("Data/loi/june_2017_east_river_loi.xlsx")

loi$soil_g <- as.numeric(loi$soil_g)

loi$om_percent <- ((loi$soil_g - (loi$baked_soil_cruc_g - loi$crucible_g)) / loi$soil_g) * 100

colnames(loi)
loi_short <- loi[, c(2,9,10)]

```

## Load total CN data, sample descriptors, column names
```{r}
#er_bulk <- read.table("Data/EA_Data/CA_ER_bulk_6Nov2017.txt", sep="\t") #out of order, corrected below
er_heavy <- read.table("Data/EA_Data/raw/CA_ER_heavy_7Nov2017.txt", sep="\t")
er_bulk_ed <- read_excel("Data/EA_Data/raw/CA_ER_bulk_6Nov2017_corrected.xlsx")[,-(1:4)]
er_int <- read.table("Data/EA_Data/raw/CA_ER_int_10Nov2017.txt", sep="\t")

er_redo <- read.table("Data/EA_Data/raw/CA_180920.txt", sep="\t")[-c(1:7, 16),] #Mariela re-ran these samples Sept 2018; removing all rows except samples

# Adding column names
colnames(er_heavy) <- c("full_name", "instrument_name", "sample", "sample_id", "sample_amt", 
  "N_ret_min", "N_resp", "N_wt_mg", "N_wt_pct", "N_peaktype", "N_element_name", "N_C_resp_ratio", 
  "C_ret_min", "C_resp", "C_wt_mg", "C_wt_pct", "C_peaktype", "C_element_name", "C_C_resp_ratio")

colnames(er_int) <- c("full_name", "instrument_name", "sample", "sample_id", "sample_amt", 
  "N_ret_min", "N_resp", "N_wt_mg", "N_wt_pct", "N_peaktype", "N_element_name", "N_C_resp_ratio", 
  "C_ret_min", "C_resp", "C_wt_mg", "C_wt_pct", "C_peaktype", "C_element_name", "C_C_resp_ratio")

colnames(er_redo) <- c("full_name", "instrument_name", "sample", "sample_id", "sample_amt", 
  "N_ret_min", "N_resp", "N_wt_mg", "N_wt_pct", "N_peaktype", "N_element_name", "N_C_resp_ratio", 
  "C_ret_min", "C_resp", "C_wt_mg", "C_wt_pct", "C_peaktype", "C_element_name", "C_C_resp_ratio")

# Adding sample IDs for er_redo
er_redo$sample_id <- c("31-1", "31-2", "27-1", "27-2", "60-1", "60-2", "40-1", "40-2")

# Changing sample_id to "sample-rep"
colnames(er_redo)[4] <- "sample_rep"
colnames(er_bulk_ed)[1] <- "sample_rep"

# Adding fraction = bulk to er_redo and er_bulk_ed
er_redo$fraction <- "bulk"
er_bulk_ed$fraction <- "bulk"

# Split fraction and sample name
er_heavy <- er_heavy %>%
  separate(sample_id, c("fraction", "sample_rep"), "_")

er_int <- er_int %>%
  separate(sample_id, c("fraction", "sample_rep"), "_")

# remove standards from er_int
er_int <- er_int[grepl("int", er_int$fraction), ]

# Select columns
er_bulk_ed <- er_bulk_ed[,c("fraction", "sample_rep", "sample_amt", "N_wt_mg", "N_wt_pct", "C_wt_mg", "C_wt_pct")]
er_heavy <- er_heavy[,c("fraction", "sample_rep", "sample_amt", "N_wt_mg", "N_wt_pct", "C_wt_mg", "C_wt_pct")]
er_int <- er_int[,c("fraction", "sample_rep", "sample_amt", "N_wt_mg", "N_wt_pct", "C_wt_mg", "C_wt_pct")]
er_redo <- er_redo[,c("fraction", "sample_rep", "sample_amt", "N_wt_mg", "N_wt_pct", "C_wt_mg", "C_wt_pct")]
```

## Add soil weights for bulk-redo data
```{r}
# read in soil weights for bulk-redo samples (weight 4/20/2018)
redo_weights <- read.csv("Data/EA_Data/20April2018_EA-bulk-redo-soilweights.csv")
redo_vector <- redo_weights$sample_amt
# Add missing sample weights
er_redo$sample_amt <- redo_vector

# Calculate actual C & N amounts
er_redo$N_wt_mg <- as.numeric(as.character(er_redo$N_wt_mg))
er_redo$C_wt_mg <- as.numeric(as.character(er_redo$C_wt_mg))

# Recalc C & N weight percentages
er_redo$N_wt_pct_recalc <- (er_redo$N_wt_mg / er_redo$sample_amt) * 100
er_redo$C_wt_pct_recalc <- (er_redo$C_wt_mg / er_redo$sample_amt) * 100

# Remove old N and C wt_pct columns, and rename the recalc columns
er_redo <- subset(er_redo, select = -c(N_wt_pct, C_wt_pct))
colnames(er_redo)[c(6,7)] <- c("N_wt_pct", "C_wt_pct")

# Remove re-run samples in er_bulk_ed
remove <- c("31-1", "31-2", "27-1", "27-2", "60-2", "40-1", "40-2")

er_bulk_ed_removed <- er_bulk_ed[!(er_bulk_ed$sample_rep) %in% remove, ]
```

## Combine bulk, intermediate, and heavy fraction data
```{r}
# Row-bind with er_bulk_ed (make sure columns are correct)
er_bulk_total <- rbind(er_redo, er_bulk_ed_removed)

# Row-bind with er_int and er_heavy
er_totalC_total <- rbind(er_bulk_total, er_int, er_heavy)

```

## Prep all fraction data (bulk, intermediate, heavy)
```{r}
# Separate "sample-rep"
er_totalC_total <- er_totalC_total %>%
  separate(sample_rep, c("ID", "rep", "composite_number"), "-")

er_totalC_total$ID <- as.numeric(er_totalC_total$ID)

# Make column for composite
er_totalC_total$composite <- ifelse(er_totalC_total$rep == "comp", "Y", "N")

ggplot(er_totalC_total) +
  aes(x=ID, y=C_wt_pct, color=rep) +
  geom_point()

# Average the sample reps
er_totalC_av <- er_totalC_total %>%
  group_by(ID, fraction, composite) %>%
  summarize(C_mean_wt_percent = mean(C_wt_pct), N_mean_wt_percent = mean(N_wt_pct), C_sd = sd(C_wt_pct), N_sd = sd(N_wt_pct))

# Merge with LOI data (bulk samples from June 2017, measured Aug 2019)
er_totalC_av_loi <- merge(er_totalC_av, loi_short, all.x=TRUE)


# Read in sample key
sample_key <- read.csv("Data/June2017_EastRiver_samplekey.csv")

# Separate the "sample" column into two separate columns (location, rep)
sample_key <- sample_key %>%
  separate(sample, c("location", "rep"), "-")

# Separate the "depth_cm" column into two separate columns (top_cm, btm_cm)
sample_key <- sample_key %>%
  separate(depth_cm, c("top_cm", "btm_cm"), "-")

# Remove "b" from rep column
sample_key$rep <- gsub("[^0-9\\.]", "", sample_key$rep)
#sample_key$location <- gsub("[^0-9\\.]", "", sample_key$location) 

# Convert the soil depths to numeric, so R treats them as numbers (and not characters).
sample_key$top_cm <- as.numeric(sample_key$top_cm)
sample_key$btm_cm <- as.numeric(sample_key$btm_cm)

# Change order
#sample_key <- sample_key[order(sample_key$location, sample_key$rep), ]

# Merge the total CN data with the sample key, using the common column "ID".
total_er_cn <- merge(sample_key, er_totalC_av_loi, by="ID", all.y=TRUE)

# Add date-year column
total_er_cn$date <- "june_2017"

# Adding info to intermediate composite samples
# From October2017_EastRiver_CLS_sampleIDlist.xlsx
#1-int-comp = MC1, 17-39cm
#2-int-comp = MC1, 54-75cm
#3-int-comp = MC2, 18-35cm
#4-int-comp = MC2, 73-85cm
#5-int-comp = MC3, 15-34cm
#6-int-comp = MC3, 50-88cm
#7-int-comp = MC3, 105-140cm

ID <- c(1:7)
location <- c("MC1", "MC1", "MC2", "MC2", "MC3", "MC3", "MC3")
top_cm <- c(17, 54, 18, 73, 15, 50, 105)
btm_cm <- c(39, 75, 35, 85, 34, 88, 140)
rep <- rep(NA, 7)
fraction <- rep("int", 7)
composite <- rep("Y", 7)
date <- rep("june_2017", 7)

int_comp <- data.frame(ID, location, top_cm, btm_cm)
int_comp$location <- as.character(int_comp$location)

# Fill in missing data in total_er_cn
total_er_cn_noNA <- left_join(total_er_cn, int_comp, by="ID") %>%
  mutate(location = coalesce(location.x, location.y)) %>%
  mutate(top_cm = coalesce(top_cm.x, btm_cm.y)) %>%
  mutate(btm_cm = coalesce(btm_cm.x, btm_cm.y)) %>%
  select(ID, location, rep, top_cm, btm_cm, fraction, composite, date, C_mean_wt_percent, N_mean_wt_percent, C_sd, N_sd, om_percent)

# Order the columns
total_er_cn_noNA <- total_er_cn_noNA[order(total_er_cn_noNA$composite, total_er_cn_noNA$fraction, total_er_cn_noNA$location), ]

#Export as csv
#write.csv(total_bulk_cn, "Data/EA_data/25April2018_EA_bulk_processed.csv")
#write.csv(total_er_cn_noNA, "Data/EA_data/EA_bulk_dens-fractions_2017_processed.csv")
```

## C:N ratios (both uncorrected & corrected for fraction of total mass)
```{r}
# Make C:N column
total_er_cn_noNA$CN <- total_er_cn_noNA$C_mean_wt_percent / total_er_cn_noNA$N_mean_wt_percent

# Export as csv
#write.csv(total_cn_comp_av, "Data/EA_data/25April2018_EA_total_cn_comp_processed.csv")
#write.csv(total_er_cn_noNA, "Data/EA_data/EA_bulk_dens-fractions_CN_2017_processed.csv")

# Corrected CN in intermediate and heavy fractions, as fraction of total mass
dens.frac.merge <- read.csv("Data/0.processed_data/EA_dens-fractionation_2017_processed.csv")[,-c(1,3:6,11)]
colnames(dens.frac.merge)[c(4,5)] <- c("top_cm", "btm_cm")
dens.frac.merge$btm_cm <- as.numeric(dens.frac.merge$btm_cm)

# Remove "b" from rep column
dens.frac.merge$rep <- gsub("[^0-9\\.]", "", dens.frac.merge$rep)

# Gathering data
dens.frac.merge_long <- dens.frac.merge %>%
  gather(fraction, frac_of_total, c(6:8))

# Change fraction names
dens.frac.merge_long$fraction <- ifelse(dens.frac.merge_long$fraction == "int_frac_percent", "int",
                                         ifelse(dens.frac.merge_long$fraction == "heavy_frac_percent", "heav", "light"))

# Merge with total_er_cn_noNA
total_er_cn_dens_frac <- merge(dens.frac.merge_long, total_er_cn_noNA, all=TRUE)
total_er_cn_dens_frac$date <- "june_2017"

total_er_cn_dens_frac$frac_of_total[total_er_cn_dens_frac$fraction == "bulk"] <- 1

total_er_cn_dens_frac$composite <- ifelse(total_er_cn_dens_frac$ID %in% c(1:7), "Y", "N")

# Calculate %C and N by mass fraction, correct C:N ratios
total_er_cn_dens_frac$C_percent_by_mass <- total_er_cn_dens_frac$C_mean_wt_percent * total_er_cn_dens_frac$frac_of_total
total_er_cn_dens_frac$N_percent_by_mass <- total_er_cn_dens_frac$N_mean_wt_percent * total_er_cn_dens_frac$frac_of_total
total_er_cn_dens_frac$CN_by_mass <- total_er_cn_dens_frac$C_percent_by_mass / total_er_cn_dens_frac$N_percent_by_mass

ggplot(total_er_cn_dens_frac) +
  aes(x=location, y=C_percent_by_mass, color=fraction) +
  geom_boxplot() +
  xlab("soil depth (cm)") + ylab("%C by mass fraction")

# Order the columns
total_er_cn_dens_frac <- total_er_cn_dens_frac[order(total_er_cn_dens_frac$location, total_er_cn_dens_frac$fraction, total_er_cn_dens_frac$composite), ]

#Export as csv
#write.csv(total_er_cn_noNA, "Data/EA_data/EA_bulk_dens-fractions_mass-frac_2017_processed.csv")


```

## Figures
```{r}
ggplot(total_loi) +
  aes(x=top_cm, y=om_percent, color=location) +
  geom_point(size=5) +
  theme_bw()

ggplot(total_er_cn_noNA) +
  aes(x=C_mean_wt_percent, y=om_percent, color=location) +
  geom_point(size=5) + geom_smooth(method="lm") +
  theme_bw()

```

## Old code
```{r}
# Make summary tables as above

# 1. As individual samples
# Amend the column headers
colnames(test_int_short)[c(2:4)] <- c("int_C_massfrac", "int_N_massfrac", "int_CN_massfrac")
colnames(test_heavy_short)[c(6:8)] <- c("heavy_C_massfrac", "heavy_N_massfrac", "heavy_CN_massfrac")

# Merge by ID
total_cn_massfrac <- merge(test_int_short, test_heavy_short, by="ID", all=TRUE)
#total_cn_massfrac <- total_cn_massfrac[order(total_cn_massfrac$location.y, total_cn_massfrac$bottom.y, total_cn_massfrac$rep.y) ,]

# Remove "b" from rep column
total_cn_massfrac$rep <- gsub("[^0-9\\.]", "", total_cn_massfrac$rep)
total_cn_massfrac <- total_cn_massfrac[order(total_cn_massfrac$location, total_cn_massfrac$rep, total_cn_massfrac$top), ]


# Export as csv
#write.csv(total_cn_massfrac, "Data/EA_data/25April2018_EA_total_cn_massfrac_processed.csv")

# 2. As composite samples
# Merge with composite data
total_cn_massfrac_comp <- merge(total_cn_massfrac, comp, by="ID")

# Average by comp
total_cn_massfrac_comp_av <- total_cn_massfrac_comp %>%
  group_by(sample_label, location_title) %>%
  summarize(
#    bulk_C = mean(bulk_C), bulk_N = mean(bulk_N), bulk_CN = mean(bulk_CN),
    int_C_massfrac = mean(int_C_massfrac, na.rm=TRUE), int_N_massfrac = mean(int_N_massfrac, na.rm=TRUE), int_CN_massfrac = mean(int_CN_massfrac, na.rm=TRUE),
    heavy_C_massfrac = mean(heavy_C_massfrac), heavy_N_massfrac = mean(heavy_N_massfrac), heavy_CN_massfrac = mean(heavy_CN_massfrac))

# Export as csv
#write.csv(total_cn_massfrac_comp_av, "Data/EA_data/25April2018_EA_total_cn_massfrac_comp_processed.csv")

```

## Total P (from Derek, LBNL)
```{r}
# Import data
totalp <- read_excel("Data/total_p/Floodplain_Total_Phosphorus.xlsx")

totalp <- totalp %>%
  separate(sample, c("location", "rep"), "-")

colnames(totalp)[12] <- "p_mg_kg"
colnames(totalp)[13] <- "p_sd"

# Convert to mmol/g
# P molar mass: 30.973762 g/mol
# X mg/kg * (1 kg/1000 g) * (1 mol/30.97g) * (1 g / 1000 mg) * (1000 mmol/1 mol)

totalp$p_mmol_g <- totalp$p_mg_kg * (1/1000) * (1/30.973762) * (1/1000) * (1000)
totalp$p_mmol_g_sd <- totalp$p_sd * (1/1000) * (1/30.973762) * (1/1000) * (1000)

# Merge with sample key
# Read in the sample key file
sample_key <- read.csv("Data/June2017_EastRiver_samplekey.csv")

# Separate the "sample" column into two separate columns (location, rep)
sample_key <- sample_key %>%
  separate(sample, c("location", "rep"), "-")

# Separate the "depth_cm" column into two separate columns (top_cm, btm_cm)
sample_key <- sample_key %>%
  separate(depth_cm, c("top_cm", "btm_cm"), "-")

# Convert the soil depths to numeric, so R treats them as numbers (and not characters).
sample_key$top_cm <- as.numeric(sample_key$top_cm)
sample_key$btm_cm <- as.numeric(sample_key$btm_cm)

## Depth categories
sample_key$depth_category <- ifelse(sample_key$top_cm < 40, "shallow", ifelse(sample_key$top_cm > 90, "deep", "subsurface"))

# Make "depth_category" a factor, and order the depth classes
sample_key$depth_category <- factor(sample_key$depth_category, levels = c("shallow", "subsurface", "deep"))
sample_key$location <- factor(sample_key$location)


# Merge the total P data with the sample key, using the common column "ID".
p_total_key <- merge(totalp, sample_key, by=c("ID", "location", "rep"))
p_total_key$depth_category <- factor(p_total_key$depth_category, levels = unique(p_total_key$depth_category))

p_processed <- p_total_key %>%
  group_by(location, depth_category) %>%
  summarise(p_mean= mean(p_mmol_g), p_sd= sd(p_mmol_g))


ggplot(subset(p_processed, depth_category %in% c("shallow", "subsurface"))) +
  aes(y=p_mean, x=depth_category, fill=depth_category) +
  geom_bar(stat="identity", position="dodge") +
  geom_errorbar(aes(ymin=p_mean-p_sd, ymax=p_mean+p_sd), width=.2, position="dodge") +
  coord_flip() +
  facet_grid(location~.) +
  xlab("") + ylab(expression(Phosphorus~(mmol~g^-1))) +
  theme_bw() +
  theme(axis.text = element_text(size = 30),
        axis.title = element_text(size = 35),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.y = element_text(size = 35),
        legend.position="none") +
  scale_fill_manual(name="",
                    breaks=c("shallow", "subsurface"),
                    labels=c("Shallow", "Subsurface"),
                    values=c("#333333","#CCCCCC"))


```
