---
title: "EastRiver_Acclima"
author: "CGA"
date: "June 4, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load necessary packages
library(tidyverse)
library(readxl)
library(gridExtra)
library(lubridate)
# Set working directory
setwd("~/east-river/")
```

## Load and tidy Acclima logger files
```{r}
mc4 <- read.csv("Data/acclima_raw/DataSnapExport_260920191115_datasnap3_mc4.csv")
mc3 <- read.csv("Data/acclima_raw/DataSnapExport_260920191112_datasnap1_mc3.csv")
mc1 <- read.csv("Data/acclima_raw/DataSnapExport_260920191103_datasnap2_mc1.csv")

# change column names
colnames(mc4) <- c("time", "sensor", "name", "moisture", "temperature", "permittivity", "conductivity", "ec", "datasnap")
colnames(mc3) <- c("time", "sensor", "name", "moisture", "temperature", "permittivity", "conductivity", "ec", "datasnap")
colnames(mc1) <- c("time", "sensor", "name", "moisture", "temperature", "permittivity", "conductivity", "ec", "datasnap")

# make sensor a factor
mc4$sensor <- as.factor(mc4$sensor)
mc3$sensor <- as.factor(mc3$sensor)
mc1$sensor <- as.factor(mc1$sensor)

# time column
mc4$time <- as.POSIXct(mc4$time, format="%m/%d/%Y %I:%M:%S %p")
mc3$time <- as.POSIXct(mc3$time, format="%m/%d/%Y %I:%M:%S %p")
mc1$time <- as.POSIXct(mc1$time, format="%m/%d/%Y %I:%M:%S %p")

# location column
mc4$location <- "MCT2-4"
mc3$location <- "MCT2-3"
mc1$location <- "MCT2-1"
```


## Name soil depths, rbind all, average by position/depth
```{r}
# initially, labeled: surface, mid_30cm, deep_70cm

mc4$depth_cm <- -999
mc4$depth_cm <- ifelse(mc4$sensor %in% c(9000094, 9000101), "15",
                    ifelse(mc4$sensor %in% c(9000218, 9000128), "30", "70"))

mc3$depth_cm <- -999
mc3$depth_cm <- ifelse(mc3$sensor %in% c(9000013, 9000109), "15",
                    ifelse(mc3$sensor %in% c(9000028, 9000230), "30", "70"))

mc1$depth_cm <- -999
mc1$depth_cm <- ifelse(mc1$sensor %in% c(9000014, 9000176), "15",
                    ifelse(mc1$sensor %in% c(9000170, 9000180), "30", "70"))

acclima_total <- rbind(mc1, mc3, mc4)

# Average by date/time & position/depth
acclima_total$year <- year(acclima_total$time)
acclima_total$month <- month(acclima_total$time)
acclima_total$day <- day(acclima_total$time)
acclima_total$hour <- hour(acclima_total$time)

acclima_av <- acclima_total %>%
  group_by(year, month, day, hour, location, depth_cm) %>%
  summarize(moisture_mean = mean(moisture, na.rm=TRUE)) %>%
  mutate(date = make_datetime(year, month, day, hour))

```


## Plots (moisture/temp)
```{r}
soil_sampling2019 <- c("2019-06-04 00:00:00", "2019-06-15 00:00:00", "2019-07-12 00:00:00", "2019-07-22 00:00:00")
soil_sampling2019 <- as.POSIXct(soil_sampling2019)
soil_sampling2019 <- data.frame(soil_sampling2019)

soil_sampling <- merge(discharge, soil_sampling)


ggplot(acclima_total[which(acclima_total$time > "2019-05-20 12:00:00"), ]) +
  aes(x=time, y=temperature, color=depth_cm) +
  geom_point(size = 1) +
  xlab("time") + ylab("temperature (C)") + ggtitle("Soil temperature") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  facet_wrap(~location) +
  guides(color=guide_legend(title="Sensor depth (cm)"))


lims_2018 <- as.POSIXct(strptime(c("2018-06-02 00:00:00", "2018-10-09 00:00:00"), format = "%Y-%m-%d %H:%M"))

lims_2019 <- as.POSIXct(strptime(c("2019-06-02 00:00:00", "2019-10-09 00:00:00"), format = "%Y-%m-%d %H:%M"))


# Name transect positions 1, 3, 4
position_names <- c(
                    "MCT2-1" = "1",
                    "MCT2-3" = "3",
                    "MCT2-4" = "4"
                    )

# Colorblind palette with grey:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")




# 2018 moisture
ggplot(subset(acclima_total, location %in% c("MCT2-1", "MCT2-3"))) +
  aes(x=time, y=moisture, color=depth_cm) +
  geom_point(size = 1) +
  ylab("Soil moisture (volumetric)") +
  scale_x_datetime(date_breaks = "1 month", date_labels = "%B") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        strip.text.x = element_blank(),
        axis.text.y = element_text(size = 15),
        axis.title = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  facet_grid(~location) +
  guides(color=guide_legend(title="Sensor depth (cm)")) +
  xlim(lims_2018)


# 2019 moisture
ggplot(subset(acclima_total, location %in% c("MCT2-1", "MCT2-3"))) +
  aes(x=time, y=moisture, color=depth_cm) +
  geom_point(size = 1) +
#  geom_vline(xintercept = as.POSIXct(as.Date(c("2019-06-04 00:00:00", "2019-06-15 00:00:00", "2019-07-12 00:00:00", "2019-07-22 00:00:00"))), linetype=4, color="black") +
 # geom_vline(aes(xintercept=as.numeric(x[c(13, 24)])), linetype=4, colour="black") +
  ylab("Soil moisture (volumetric)") +
  scale_x_datetime(date_breaks = "1 month", date_labels = "%B") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        strip.text.x = element_blank(),
        axis.text = element_text(size = 22),
        axis.title = element_text(size = 22),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  facet_grid(~location) + #formerly (location~.) for vertical stacking
  guides(color=guide_legend(title="Sensor depth (cm)")) +
  xlim(lims_2019)






ggplot(acclima_total[which(acclima_total$time > "2019-05-20 12:00:00"), ]) +
  aes(x=time, y=conductivity, color=depth_cm) +
  geom_point(size = 1) +
  xlab("time") + ylab("conductivity") + ggtitle("Soil conductivity") +
  theme_bw() +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  facet_wrap(~location) +
  guides(color=guide_legend(title="Sensor depth (cm)"))

```