---
title: "EastRiver_rhizon"
author: "CGA"
date: "November 1, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
```

## Load files, separate gas data into separate files
```{r, echo=FALSE}
rhizon_weight <- read_excel("Data/EastRiver_rhizons/MCT2_rhizon_vial_weights.xlsx")[,-7]
rhizon_gas <- read_excel("Data/EastRiver_rhizons/MCT2_rhizon_co2_summer2018.xlsx")

# Gas data separated by unique file names
unique(rhizon_gas$filename)
gas1 <- subset(rhizon_gas, filename=="CA10182018_b")
gas2 <- subset(rhizon_gas, filename=="CA10232018_a")
gas3 <- subset(rhizon_gas, filename=="CA10242018_a")
gas4 <- subset(rhizon_gas, filename=="CA10242018_b")
gas5 <- subset(rhizon_gas, filename=="CA10242018_c")
gas6 <- subset(rhizon_gas, filename=="CA10252018_a")
gas7 <- subset(rhizon_gas, filename=="CA10252018_b")
gas8 <- subset(rhizon_gas, filename=="CA10252018_c")
gas9 <- subset(rhizon_gas, filename=="CA10312018_a") # gas well data
```

## Standard curves and convert area to concentration
```{r, echo=FALSE}

## Make standard curves for each data file, convert area to concentration in main file.

#gas1
gas1_std <- gas1[c(1:3), ]
gas1_std$mct2_position_or_standard <- as.numeric(gas1_std$mct2_position_or_standard) #convert ppm to numeric
plot(gas1_std$mct2_position_or_standard, gas1_std$area) #plot
gas1_lm <- lm(area ~ mct2_position_or_standard, data=gas1_std)
abline(gas1_lm, col="red")
summary(gas1_lm)
coef(gas1_lm) #b=0.94712978, m=0.03382774

gas1$conc <- (gas1$area - 0.94712978) / 0.03382774


#gas2
gas2_std <- gas2[c(1:3), ]
gas2_std$mct2_position_or_standard <- as.numeric(gas2_std$mct2_position_or_standard) #convert ppm to numeric
plot(gas2_std$mct2_position_or_standard, gas2_std$area) #plot
summary(lm(area ~ mct2_position_or_standard, data=gas2_std))
coef(lm(area ~ mct2_position_or_standard, data=gas2_std)) #b=-2.34870285, m=0.03420157

gas2$conc <- (gas2$area - -2.34870285) / 0.03420157


#gas3
gas3_std <- gas3[c(1:3), ]
gas3_std$mct2_position_or_standard <- as.numeric(gas3_std$mct2_position_or_standard) #convert ppm to numeric
plot(gas3_std$mct2_position_or_standard, gas3_std$area) #plot
summary(lm(area ~ mct2_position_or_standard, data=gas3_std))
coef(lm(area ~ mct2_position_or_standard, data=gas3_std)) #b=-5.60406984, m=0.03595289

gas3$conc <- (gas3$area - -5.60406984) / 0.03595289


#gas4
gas4_std <- gas4[c(1:3), ]
gas4_std$mct2_position_or_standard <- as.numeric(gas4_std$mct2_position_or_standard) #convert ppm to numeric
plot(gas4_std$mct2_position_or_standard, gas4_std$area) #plot
summary(lm(area ~ mct2_position_or_standard, data=gas4_std))
coef(lm(area ~ mct2_position_or_standard, data=gas4_std)) #b=-1.55119086, m=0.03520806

gas4$conc <- (gas4$area - -1.55119086) / 0.03520806


#gas5
gas5_std <- gas5[c(1:3), ]
gas5_std$mct2_position_or_standard <- as.numeric(gas5_std$mct2_position_or_standard) #convert ppm to numeric
plot(gas5_std$mct2_position_or_standard, gas5_std$area) #plot
summary(lm(area ~ mct2_position_or_standard, data=gas5_std))
coef(lm(area ~ mct2_position_or_standard, data=gas5_std)) #b=-5.62501624, m=0.03635478

gas5$conc <- (gas5$area - -5.62501624) / 0.03635478


#gas6
gas6_std <- gas6[c(1:3), ]
gas6_std$mct2_position_or_standard <- as.numeric(gas6_std$mct2_position_or_standard) #convert ppm to numeric
plot(gas6_std$mct2_position_or_standard, gas6_std$area) #plot
summary(lm(area ~ mct2_position_or_standard, data=gas6_std))
coef(lm(area ~ mct2_position_or_standard, data=gas6_std)) #b=-0.14534376, m=0.03513982

gas6$conc <- (gas6$area - -0.14534376) / 0.03513982


#gas7
gas7_std <- gas7[c(1:3), ]
gas7_std$mct2_position_or_standard <- as.numeric(gas7_std$mct2_position_or_standard) #convert ppm to numeric
plot(gas7_std$mct2_position_or_standard, gas7_std$area) #plot
summary(lm(area ~ mct2_position_or_standard, data=gas7_std))
coef(lm(area ~ mct2_position_or_standard, data=gas7_std)) #b=-8.76704452, m=0.04025636

gas7$conc <- (gas7$area - -8.76704452) / 0.04025636


#gas8
gas8_std <- gas8[c(1:3), ]
gas8_std$mct2_position_or_standard <- as.numeric(gas8_std$mct2_position_or_standard) #convert ppm to numeric
plot(gas8_std$mct2_position_or_standard, gas8_std$area) #plot
summary(lm(area ~ mct2_position_or_standard, data=gas8_std))
coef(lm(area ~ mct2_position_or_standard, data=gas8_std)) #b=-7.32163591, m=0.04024577

gas8$conc <- (gas8$area - -7.32163591) / 0.04024577


#gas9
gas9_std <- gas9[c(1:3), ]
gas9_std$mct2_position_or_standard <- as.numeric(gas9_std$mct2_position_or_standard) #convert ppm to numeric
plot(gas9_std$mct2_position_or_standard, gas9_std$area) #plot
summary(lm(area ~ mct2_position_or_standard, data=gas9_std))
coef(lm(area ~ mct2_position_or_standard, data=gas9_std)) #b=-13.49328478, m=0.03723908

gas9$conc <- (gas9$area - 0.94712978) / 0.03382774


```


## Take only the samples, clean up the data
```{r}
## Subset only the samples
gas1 <- subset(gas1, sample_standard %in% "sample")
gas2 <- subset(gas2, sample_standard %in% "sample")
gas3 <- subset(gas3, sample_standard %in% "sample")
gas4 <- subset(gas4, sample_standard %in% "sample")
gas5 <- subset(gas5, sample_standard %in% "sample")
gas6 <- subset(gas6, sample_standard %in% "sample")
gas7 <- subset(gas7, sample_standard %in% "sample")
gas8 <- subset(gas8, sample_standard %in% "sample")
gas9 <- subset(gas9, sample_standard %in% "sample")

## Take out the samples that were re-run (on CA10242018_c = 'gas5'; see column in datafile for notes)
gas5 <- gas5[-c(36:50), ]

## rbind all gas data together  
gas_total <- rbind(gas1, gas2, gas3, gas4, gas5, gas6, gas7, gas8) #not rbinding gas9, since that is gas well data

## Fill in missing data
# Convert date from excel numbers to actual dates
gas_total$date <- as.numeric(gas_total$date)
gas_total$date <- excel_numeric_to_date(gas_total$date)

# If date blank, then: 5/27/2018
gas_total$date[is.na(gas_total$date)] <- "2018-05-27"

# Remove irrelevant columns
colnames(gas_total)
gas_total <- gas_total[ ,-c(2,7,9,10)]

# Change "surf" to "0-10"
gas_total$depth_cm[gas_total$depth_cm == "surf"] <- "0-10"

# Change "?" to "2", for MCT2-4, 70-80cm, 6/18/2018
gas_total$environment[gas_total$environment == "?"] <- "2"

# Change column names
colnames(gas_total)
colnames(gas_total)[2] <- "mct2_position"

```


## Match up with the vial weights
```{r}
# Change rhizon vials column names
colnames(rhizon_weight) <- c("date", "mct2_position", "environment", "depth_cm", "flask_type", "weight_g")

# Convert date from excel numbers to actual dates
rhizon_weight$date <- as.numeric(rhizon_weight$date)
rhizon_weight$date <- excel_numeric_to_date(rhizon_weight$date)

# If date blank, then: 5/27/2018
rhizon_weight$date[is.na(rhizon_weight$date)] <- "2018-05-27"

# Change to lowercase
rhizon_weight$environment <- tolower(rhizon_weight$environment)

## Make changes to match gas data nomenclature
# Change "by river" to "rw"
rhizon_weight$environment[rhizon_weight$environment == "by river"] <- "rw"

# Change "un" to "2", for MCT2-4, 70-80cm, 6/18/2018
rhizon_weight$environment[rhizon_weight$environment == "un"] <- "2"

# Change "34-44" to "30-40" for MCT2-4, env 2, 6/1/2018 & 6/10/2018
rhizon_weight$depth_cm[rhizon_weight$depth_cm == "34-44"] <- "30-40"

# Change "35-45" to "30-40" for MCT2-1, env rw, 6/1/2018 & 6/10/2018
rhizon_weight$depth_cm[rhizon_weight$depth_cm == "35-45"] <- "30-40"

# Change "63-73" to "60-70" for MCT2-4, env 2, 6/1/2018 & 6/10/2018
rhizon_weight$depth_cm[rhizon_weight$depth_cm == "63-73"] <- "60-70"

# Change "65-75" to "60-70" for MCT2-4, env 1, 6/1/2018 & 6/10/2018
rhizon_weight$depth_cm[rhizon_weight$depth_cm == "65-75"] <- "60-70"

# Separate data by position & date to help fill in missing data points
gas_total1 <- subset(gas_total, mct2_position == 1)
gas_total3 <- subset(gas_total, mct2_position == 3)
gas_total4 <- subset(gas_total, mct2_position == 4)

rhizon_weight1 <- subset(rhizon_weight, mct2_position == 1)
rhizon_weight3 <- subset(rhizon_weight, mct2_position == 3)
rhizon_weight4 <- subset(rhizon_weight, mct2_position == 4)



# Test merges
test1 <- merge(gas_total1, rhizon_weight1)
test3 <- merge(gas_total3, rhizon_weight3) #120; should be 114 (6 extra)
test4 <- merge(gas_total4, rhizon_weight4)

# Total merge
rhizon_total <- rbind(test1, test3, test4)

```


## Apply Henry's Law to get concentrations
```{r}
# Subtract vial weight from total weight (need square & tapered vial weights)
mean(22.7482, 22.8133) # tapered mean = 22.7482
mean(15.9533, 16.0742, 16.1808) # square mean = 15.9533

rhizon_total$flask_g <- ifelse(rhizon_total$flask_type == "tapered", 22.7482, 15.9533)

rhizon_total$water_g <- rhizon_total$weight_g - rhizon_total$flask_g

rhizon_total$water_L <- rhizon_total$water_g * 0.001 #convert g to L; water = 0.001 g/L

# Take out empty rhizons (NEED TO MATCH UP WITH KEY)
rhizon_total <- subset(rhizon_total, water_g > 0.15)


# Use Henry's Law
# Total gas concentration (TC) in the original water sample is calculated by determining the concentration of headspace and converting this to the partial pressure and then solving for the aqueous concentration which partitioned in the gas phase (CAH) and the concentration remaining in the aqueous phase (CA). The total concentration of gas in original sample (TC) is the sum of the concentration partitioned in the gas phase (CAH) and the concentration remaining in the aqueous phase (CA).

# Henry's law states that the mole fraction of a dissolved gas (Xg) is equal to the partial pressure of the gas (pg) at equilibrium divided by Henry's law constant (H). Gas solubility coefficients are used to calculate Henry's law constant.

# C = P/KH
#P is the partial pressure of the gas above the solution (ppm measured directly on li-cor * 10^-6 = atm)
#KH is the Henry's law constant for the solution. Given: KH of CO2 in water = 29.41 atm/(mol/L) at 25 °C (298 K).
#C is the concentration of the dissolved gas in solution.

# C = (partial pressure CO2) / 29.41 atm(mol/L)

rhizon_total$water_mol_co2 <- ((rhizon_total$conc * (1*10^-6))/29.41) * rhizon_total$water_L
rhizon_total$air_mol_co2 <- (rhizon_total$conc) * (0.012 - rhizon_total$water_L) * (1/44.01) * (1/1000) #vials are 12ml = 0.012 L; molar mass of co2 is 44.01 g/mol; 1000 mg in g

rhizon_total$total_mol_co2 <- rhizon_total$water_mol_co2 + rhizon_total$air_mol_co2
rhizon_total$dic_aq <- rhizon_total$total_mol_co2 / rhizon_total$water_L

# Adding depth classes (surface, mid, deep)

rhizon_total$depth_class <- ifelse(rhizon_total$depth_cm == "0-10", "surface",
                                   ifelse(rhizon_total$depth_cm == "30-40", "30-40",
                                          ifelse(rhizon_total$depth_cm == "60-70", "60-80",
                                                 ifelse(rhizon_total$depth_cm == "70-80", "60-80",
                                                        ifelse(rhizon_total$depth_cm == "80-90", "80-100", "80-100")))))

```


## Preliminary figures
```{r}
rhizon_total$depth_class <- factor(rhizon_total$depth_class, levels = c("surface", "30-40", "60-80", "80-100"))

ggplot(subset(rhizon_total, mct2_position %in% c(1,3))) +
  aes(x=date, y=dic_aq, color=as.factor(mct2_position)) +
  geom_point() +
  geom_smooth() +
  xlab("Date") + ylab("DIC (mol)") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 25),
        strip.text.y = element_text(size = 20),
        legend.title=element_text(size=20),
        legend.text=element_text(size=20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  guides(color=guide_legend(title="Transect")) +
  scale_colour_manual(values = c("1" = "#000000", "3" = "#E69F00", "4" = "#56B4E9")) +
  facet_grid(depth_class~.)

ggplot(subset(rhizon_total, mct2_position %in% c(4))) +
  aes(x=date, y=dic_aq, color=as.factor(mct2_position)) +
  geom_point() +
  geom_smooth() +
  xlab("Date") + ylab("DIC (mol)") +
  theme_bw() +
  theme(axis.text = element_text(size = 25),
        axis.title = element_text(size = 25),
        strip.text.y = element_text(size = 20),
        legend.title=element_text(size=20),
        legend.text=element_text(size=20),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  guides(color=guide_legend(title="Transect")) +
  scale_colour_manual(values = c("1" = "#000000", "3" = "#E69F00", "4" = "#56B4E9")) +
  facet_grid(depth_class~.)

```